# It's important that tests are performed against all stable-X.Y branches.
# Testing against `devel` may fail as new tests are added.
# An alternative to `devel` is the `milestone` branch.
ansible:
  - stable-2.16
  - stable-2.18
  - stable-2.20
  - stable-2.21
  - devel
python:
  - "3.11"
  - "3.12"
  - "3.13"
  - "3.14"
exclude:
  # 2.16 supports Python 3.10-3.12
  - ansible: stable-2.16
    python: "3.13"
  - ansible: stable-2.16
    python: "3.14"
  # 2.18 supports Python 3.11-3.13
  - ansible: stable-2.18
    python: "3.14"
  # 2.20 supports Python 3.12-3.14
  - ansible: stable-2.20
    python: "3.11"
  # 2.21 supports Python 3.12-3.14
  - ansible: stable-2.21
    python: "3.11"
  # devel works with Python 3.13+
  - ansible: devel
    python: "3.11"
  - ansible: devel
    python: "3.12"
