---
galaxy_info:
  role_name: gcloud
  author: Eric Anderson
  description: Ansible role to install google-cloud-sdk
  license: GPL-3.0
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
        - precise
        - trusty
        - xenial
        - bionic
  galaxy_tags:
    - gcloud
    - google
    - cloud
    - sdk
dependencies: []
