#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - '''A runtime is a Google-provisioned virtual machine (VM) that can run the code in your notebook (IPYNB file).'''
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_colab_runtime
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.notebookRuntimes)'
  - 'Create a runtime Guide: U(https://cloud.google.com/colab/docs/create-runtime)'
options:
  auto_upgrade:
    description:
      - Triggers an upgrade anytime the runtime is started if it is upgradable.
    type: bool
  description:
    description:
      - The description of the Runtime.
      - This property is immutable, to change it, you must delete and recreate the resource.
    type: str
  desired_state:
    choices:
      - RUNNING
      - STOPPED
    default: RUNNING
    description:
      - Desired state of the Colab Runtime.
      - Set this field to `RUNNING` to start the runtime, and `STOPPED` to stop it.
    type: str
  display_name:
    description:
      - The display name of the Runtime.
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    type: str
  location:
    description:
      - 'The location for the resource: https://cloud.google.com/colab/docs/locations.'
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    type: str
  name:
    description:
      - The resource name of the Runtime.
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    type: str
  notebook_runtime_template_ref:
    description:
      - '''Runtime specific information used for NotebookRuntime creation.''.'
    suboptions:
      notebook_runtime_template:
        description:
          - The resource name of the NotebookRuntimeTemplate based on which a NotebookRuntime will be created.
          - This property is immutable, to change it, you must delete and recreate the resource.
        required: true
        type: str
    type: dict
  runtime_user:
    description:
      - The user email of the NotebookRuntime.
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist in GCP.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Creates a GCP Colab.Runtime resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create Basic Runtime
  google.cloud.gcp_colab_runtime:
    state: present
    name: my-runtime
    display_name: My Runtime
    runtime_user: my-user@gmail.com
    location: us-central1
    notebook_runtime_template_ref:
      notebook_runtime_template: my-runtime-template
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

################################################################################

- name: Create Basic Runtime in Stopped State
  google.cloud.gcp_colab_runtime:
    state: present
    name: my-runtime
    display_name: My Runtime
    location: us-central1
    runtime_user: my-user@gmail.com
    notebook_runtime_template_ref:
      notebook_runtime_template: my-runtime-template
    desired_state: STOPPED
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
expirationTime:
  description:
    - Output only.
    - Timestamp when this NotebookRuntime will be expired.
  returned: success
  type: str
isUpgradable:
  description:
    - Output only.
    - Checks if the NotebookRuntime is upgradable.
  returned: success
  type: bool
notebookRuntimeType:
  description:
    - Output only.
    - The type of the notebook runtime.
  returned: success
  type: str
state:
  description:
    - Output only.
    - The state of the runtime.
  returned: success
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_utils as gcp
import types

# BEGIN Custom imports
import copy
import time

# END Custom imports


def build_link(module_params, uri):
    params = module_params.copy()

    return ("https://{location}-aiplatform.googleapis.com/v1/" + uri).format(**params)


class NotebookRuntimeTemplateRef(gcp.Resource):
    def _request(self):
        return {
            "notebookRuntimeTemplate": self.request.get("notebook_runtime_template"),
        }

    def _response(self):
        return {
            "notebookRuntimeTemplate": self.response.get("notebookRuntimeTemplate"),
        }


class Colab(gcp.Resource):
    def _request(self):
        return {
            "description": self.request.get("description"),
            "displayName": self.request.get("display_name"),
            "notebookRuntimeTemplateRef": gcp.remove_empties(
                NotebookRuntimeTemplateRef(self.request.get("notebook_runtime_template_ref", {})).to_request()
            ),  # remove empty values
            "runtimeUser": self.request.get("runtime_user"),
        }

    def _response(self):
        return {
            "description": self.response.get("description"),
            "displayName": self.response.get("displayName"),
            "expirationTime": self.response.get("expirationTime"),
            "isUpgradable": self.response.get("isUpgradable"),
            "notebookRuntimeTemplateRef": NotebookRuntimeTemplateRef().from_response(
                self.response.get("notebookRuntimeTemplateRef", {})
            ),
            "notebookRuntimeType": self.response.get("notebookRuntimeType"),
            "runtimeUser": self.response.get("runtimeUser"),
        }


################################################################################
# Main
################################################################################


def encode(self, obj):
    """
    This is a function bound to the main resource object. Its input is the object returned from to_request()
    and it mutates it before it is sent to the API.
    """
    # --------- BEGIN custom encoder code ---------
    if self._state in ["absent", "update"]:  # no encoding when making a DELETE or POST request
        return {}
    self.debug(func="encoder", encoded=False, obj=obj)
    r = {}
    tmp = copy.deepcopy(obj)
    tplRef = tmp.pop("notebookRuntimeTemplateRef", None)
    if tplRef:
        r["notebookRuntimeTemplate"] = tplRef["notebookRuntimeTemplate"]  # sub-field is required
    r["notebookRuntime"] = tmp
    self.debug(func="encoder", encoded=True, obj=r)

    return r

    # --------- END custom encoder code ---------


def decode(self, obj):
    """
    This is a function bound to the main resource object. Its input is the object returned from from_response()
    and it mutates it before it is returned to the module caller.
    """
    return obj


def main():
    """Main function"""

    module = gcp.Module(
        argument_spec=dict(
            name=dict(
                type="str",
                required=True,
            ),
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            auto_upgrade=dict(
                type="bool",
            ),
            description=dict(
                type="str",
            ),
            desired_state=dict(
                type="str",
                default="RUNNING",
                choices=["RUNNING", "STOPPED"],
            ),
            display_name=dict(
                type="str",
                required=True,
            ),
            location=dict(
                type="str",
                required=True,
            ),
            notebook_runtime_template_ref=dict(
                type="dict",
                options=dict(
                    notebook_runtime_template=dict(
                        type="str",
                        required=True,
                    )
                ),
            ),
            runtime_user=dict(
                type="str",
                required=True,
            ),
        )
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp.ResourceOpConfigs(
        {
            "base_url": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookRuntimes",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "create": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookRuntimes:assign?notebook_runtime_id={name}",
                    "async_uri": "{op_id}",
                    "verb": "POST",
                    "timeout_minutes": 20,
                }
            ),
            "delete": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookRuntimes/{name}",
                    "async_uri": "{op_id}",
                    "verb": "DELETE",
                    "timeout_minutes": 20,
                }
            ),
            "read": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookRuntimes/{name}",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "update": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookRuntimes/{name}",
                    "async_uri": "{op_id}",
                    "verb": "PUT",
                    "timeout_minutes": 20,
                }
            ),
        }
    )

    params = gcp.remove_nones(module.params)
    resource = Colab(params, module=module, product="Colab", kind="colab#runtime")
    read_uri = op_configs.read.uri

    resource._state = state  # store the state in the resource object
    # Bind the encode and decode functions to the resource object
    resource.encode_func = types.MethodType(encode, resource)
    resource.decode_func = types.MethodType(decode, resource)

    custom_diff = None  # Set this variable if you want to implement custom diff logic

    # --------- BEGIN pre-read custom code ---------
    def change_state(state_link, async_state_link, resource, retries, verb):
        """Change the state of the runtime"""

        resource._state = "update"
        async_state_func = getattr(resource, "post_async")
        return async_state_func(state_link + f":{verb}", async_link=async_state_link, retries=retries)

    # --------- END pre-read custom code ---------

    read_url = build_link(params, read_uri)
    existing_obj = resource.decode_func(resource.get(read_url, allow_not_found=True) or {})
    new_obj = {}
    gcp.debug(module, existing=existing_obj, post=False)

    if custom_diff is not None:
        is_different = custom_diff
    else:
        is_different = resource.diff(gcp.remove_empties(existing_obj))
    gcp.debug(
        module,
        request=gcp.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp.empty(existing_obj):
        if state == "present":
            create_uri = op_configs.create.uri
            create_async_uri = op_configs.create.async_uri
            try:
                # --------- BEGIN create code ---------
                is_async = create_async_uri != ""
                create_link = build_link(params, create_uri)
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                async_create_func = getattr(resource, op_configs.create.verb + "_async")
                async_create_link = build_link(params, "") + create_async_uri
                gcp.debug(
                    module,
                    msg="Creating resource",
                    create_link=create_link,
                    async_create_link=async_create_link,
                    is_async=is_async,
                )

                if is_async:
                    new_obj = async_create_func(create_link, async_link=async_create_link, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.decode_func(new_obj)
                gcp.debug(module, new=new_obj, action="create", post=False)
                # --------- BEGIN post-create custom code ---------
                # stop runtime if desired_state is STOPPED
                if params.get("desired_state") == "STOPPED":
                    gcp.debug(module, msg="Changing runtime state to STOPPED")
                    state_link = build_link(params, op_configs.update.uri)
                    state_async_uri = op_configs.update.async_uri
                    async_state_link = build_link(params, "") + state_async_uri
                    new_obj = change_state(state_link, async_state_link, resource, op_configs.update.timeout, "stop")
                # wait for runtime to reach desired state
                while True:
                    new_obj = resource.get(read_url)
                    gcp.debug(module, polling=new_obj, action="post_create")
                    if new_obj.get("runtimeState") == params.get("desired_state"):
                        break
                    time.sleep(1)

                # --------- END post-create custom code ---------
                gcp.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            delete_uri = op_configs.delete.uri
            delete_async_uri = op_configs.delete.async_uri
            try:
                # --------- BEGIN delete code ---------
                is_async = delete_async_uri != ""
                delete_link = build_link(params, delete_uri)
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                async_delete_func = getattr(resource, op_configs.delete.verb + "_async")
                async_delete_link = build_link(params, "") + delete_async_uri
                gcp.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_delete_link=async_delete_link,
                    is_async=is_async,
                )
                if is_async:
                    new_obj = async_delete_func(delete_link, async_link=async_delete_link, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.decode_func(new_obj)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                update_uri = op_configs.update.uri
                update_async_uri = op_configs.update.async_uri
                try:
                    # --------- BEGIN custom update code ---------
                    desired_state = params.get("desired_state")
                    state_link = build_link(params, update_uri)
                    async_state_link = build_link(params, "") + update_async_uri
                    if desired_state != existing_obj.get("runtimeState"):
                        gcp.debug(module, msg=f"Changing runtime state to {desired_state}")
                        new_obj = change_state(
                            state_link,
                            async_state_link,
                            resource,
                            op_configs.update.timeout,
                            "start" if desired_state == "RUNNING" else "stop",
                        )
                        # wait for runtime to reach desired state
                        while True:
                            new_obj = resource.get(read_url)
                            gcp.debug(module, polling=new_obj, action="custom_update")
                            if new_obj.get("runtimeState") == params.get("desired_state"):
                                break
                            time.sleep(1)
                    auto_upgrade = params.get("auto_upgrade", False)
                    is_upgradable = existing_obj.get("isUpgradable", False)
                    if auto_upgrade and is_upgradable:
                        gcp.debug(module, msg="Upgrading runtime")
                        new_obj = change_state(
                            state_link, async_state_link, resource, op_configs.update.timeout, "upgrade"
                        )
                    # --------- END custom update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj = resource.from_response(resource.get(read_url, allow_not_found=True) or {})
    new_obj.update({"changed": changed})
    gcp.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
