#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - '''An instance of a notebook Execution'''
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_colab_notebook_execution
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.notebookExecutionJobs)'
  - 'Schedule a notebook run Guide: U(https://cloud.google.com/colab/docs/schedule-notebook-run)'
options:
  custom_environment_spec:
    description:
      - Compute configuration to use for an execution job.
    suboptions:
      machine_spec:
        description:
          - '''The machine configuration of the runtime.''.'
        suboptions:
          accelerator_count:
            description:
              - The number of accelerators used by the runtime.
            type: int
          accelerator_type:
            description:
              - The type of hardware accelerator used by the runtime.
              - If specified, acceleratorCount must also be specified.
            type: str
          machine_type:
            description:
              - The Compute Engine machine type selected for the runtime.
            type: str
        type: dict
      network_spec:
        description:
          - The network configuration for the runtime.
        suboptions:
          enable_internet_access:
            description:
              - Enable public internet access for the runtime.
            type: bool
          network:
            description:
              - The name of the VPC that this runtime is in.
            type: str
          subnetwork:
            description:
              - The name of the subnetwork that this runtime is in.
            type: str
        type: dict
      persistent_disk_spec:
        description:
          - The configuration for the data disk of the runtime.
        suboptions:
          disk_size_gb:
            description:
              - The disk size of the runtime in GB.
              - If specified, the diskType must also be specified.
              - The minimum size is 10GB and the maximum is 65536GB.
            type: str
          disk_type:
            description:
              - The type of the persistent disk.
            type: str
        type: dict
    type: dict
  dataform_repository_source:
    description:
      - The Dataform Repository containing the input notebook.
    suboptions:
      commit_sha:
        description:
          - The commit SHA to read repository with.
          - If unset, the file will be read at HEAD.
        type: str
      dataform_repository_resource_name:
        description:
          - The resource name of the Dataform Repository.
        required: true
        type: str
    type: dict
  direct_notebook_source:
    description:
      - The content of the input notebook in ipynb format.
    suboptions:
      content:
        description:
          - The base64-encoded contents of the input notebook file.
        required: true
        type: str
    type: dict
  display_name:
    description:
      - The display name of the Notebook Execution.
    required: true
    type: str
  execution_timeout:
    description:
      - Max running time of the execution job in seconds (default 86400s / 24 hrs).
    type: str
  execution_user:
    description:
      - The user email to run the execution as.
    type: str
  gcs_notebook_source:
    description:
      - The Cloud Storage uri for the input notebook.
    suboptions:
      generation:
        description:
          - The version of the Cloud Storage object to read.
          - If unset, the current version of the object is read.
          - See https://cloud.google.com/storage/docs/metadata#generation-number.
        type: str
      uri:
        description:
          - The Cloud Storage uri pointing to the ipynb file.
        required: true
        type: str
    type: dict
  gcs_output_uri:
    description:
      - The Cloud Storage location to upload the result to.
      - Format:`gs://bucket-name`.
    required: true
    type: str
  location:
    description:
      - 'The location for the resource: https://cloud.google.com/colab/docs/locations.'
    required: true
    type: str
  notebook_execution_job_id:
    description:
      - User specified ID for the Notebook Execution Job.
    type: str
  notebook_runtime_template_resource_name:
    description:
      - The NotebookRuntimeTemplate to source compute configuration from.
    type: str
  service_account:
    description:
      - The service account to run the execution as.
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist in GCP.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Creates a GCP Colab.NotebookExecution resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create Basic Notebook Execution
  vars:
    nb_config:
      cells:
        - cell_type: code
          execution_count: null
          metadata: {}
          outputs: []
          source:
            - print('Hello, World!')
      metadata:
        kernelspec:
          display_name: Python 3
          language: python
          name: python3
        language_info:
          codemirror_mode:
            name: ipython
            version: 3
          file_extension: .py
          mimetype: text/x-python
          name: python
          nbconvert_exporter: python
          pygments_lexer: ipython3
          version: 3.8.5
      nbformat: 4
      nbformat_minor: 4
  google.cloud.gcp_colab_notebook_execution:
    state: present
    display_name: my-notebook-execution
    location: us-central1
    direct_notebook_source:
      content: "{{ nb_config | to_json | b64encode }}"
    notebook_runtime_template_resource_name: projects/{{ gcp_project }}/locations/us-central1/notebookRuntimeTemplates/my-runtime-template
    gcs_output_uri: gs://my-bucket
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

################################################################################

- name: Create Notebook Execution With Custom Environment
  vars:
    nb_config:
      cells:
        - cell_type: code
          execution_count: null
          metadata: {}
          outputs: []
          source:
            - print('Hello, World!')
      metadata:
        kernelspec:
          display_name: Python 3
          language: python
          name: python3
        language_info:
          codemirror_mode:
            name: ipython
            version: 3
          file_extension: .py
          mimetype: text/x-python
          name: python
          nbconvert_exporter: python
          pygments_lexer: ipython3
          version: 3.8.5
      nbformat: 4
      nbformat_minor: 4
  google.cloud.gcp_colab_notebook_execution:
    state: present
    display_name: my-notebook-execution
    location: us-central1
    direct_notebook_source:
      content: "{{ nb_config | to_json | b64encode }}"
    notebook_runtime_template_resource_name: projects/{{ gcp_project }}/locations/us-central1/notebookRuntimeTemplates/my-runtime-template
    custom_environment_spec:
      machine_spec:
        machine_type: n1-standard-4
        accelerator_type: NVIDIA_TESLA_T4
        accelerator_count: 1
      persistent_disk_spec:
        disk_type: pd-standard
        disk_size_gb: 100
      network_spec:
        enable_internet_access: true
        network: "projects/{{ gcp_project }}/global/networks/my-network"
    gcs_output_uri: gs://my-bucket
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

################################################################################

- name: Create Notebook Execution With Dataform Repository Source
  google.cloud.gcp_colab_notebook_execution:
    state: present
    display_name: my-notebook-execution
    location: us-central1
    dataform_repository_source:
      commit_sha: deadbeef
      dataform_repository_resource_name: projects/{{ gcp_project }}/locations/us-central1/dataform/repositories/my-dataform-repository
    notebook_runtime_template_resource_name: projects/{{ gcp_project }}/locations/us-central1/notebookRuntimeTemplates/my-runtime-template
    gcs_output_uri: gs://my-bucket
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
state:
  description: The current state of the resource.
  returned: always
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

# BEGIN Custom imports
# END Custom imports


class CustomEnvironmentSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "machineSpec": gcp_v2.remove_empties(
                CustomEnvironmentSpecMachineSpec(self.request.get("machine_spec", {})).to_request()
            ),  # remove empty values
            "networkSpec": gcp_v2.remove_empties(
                CustomEnvironmentSpecNetworkSpec(self.request.get("network_spec", {})).to_request()
            ),  # remove empty values
            "persistentDiskSpec": gcp_v2.remove_empties(
                CustomEnvironmentSpecPersistentDiskSpec(self.request.get("persistent_disk_spec", {})).to_request()
            ),  # remove empty values
        }

    def _response(self):
        return {
            "machineSpec": CustomEnvironmentSpecMachineSpec().from_response(self.response.get("machineSpec", {})),
            "networkSpec": CustomEnvironmentSpecNetworkSpec().from_response(self.response.get("networkSpec", {})),
            "persistentDiskSpec": CustomEnvironmentSpecPersistentDiskSpec().from_response(
                self.response.get("persistentDiskSpec", {})
            ),
        }


class CustomEnvironmentSpecMachineSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "acceleratorCount": self.request.get("accelerator_count"),
            "acceleratorType": self.request.get("accelerator_type"),
            "machineType": self.request.get("machine_type"),
        }

    def _response(self):
        return {
            "acceleratorCount": self.response.get("acceleratorCount"),
            "acceleratorType": self.response.get("acceleratorType"),
            "machineType": self.response.get("machineType"),
        }


class CustomEnvironmentSpecNetworkSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "enableInternetAccess": self.request.get("enable_internet_access"),
            "network": self.request.get("network"),
            "subnetwork": self.request.get("subnetwork"),
        }

    def _response(self):
        return {
            "enableInternetAccess": self.response.get("enableInternetAccess"),
            "network": self.response.get("network"),
            "subnetwork": self.response.get("subnetwork"),
        }


class CustomEnvironmentSpecPersistentDiskSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "diskSizeGb": self.request.get("disk_size_gb"),
            "diskType": self.request.get("disk_type"),
        }

    def _response(self):
        return {
            "diskSizeGb": self.response.get("diskSizeGb"),
            "diskType": self.response.get("diskType"),
        }


class DataformRepositorySource(gcp_v2.Resource):
    def _request(self):
        return {
            "commitSha": self.request.get("commit_sha"),
            "dataformRepositoryResourceName": self.request.get("dataform_repository_resource_name"),
        }

    def _response(self):
        return {
            "commitSha": self.response.get("commitSha"),
            "dataformRepositoryResourceName": self.response.get("dataformRepositoryResourceName"),
        }


class DirectNotebookSource(gcp_v2.Resource):
    def _request(self):
        return {
            "content": self.request.get("content"),
        }

    def _response(self):
        return {
            "content": self.response.get("content"),
        }


class GcsNotebookSource(gcp_v2.Resource):
    def _request(self):
        return {
            "generation": self.request.get("generation"),
            "uri": self.request.get("uri"),
        }

    def _response(self):
        return {
            "generation": self.response.get("generation"),
            "uri": self.response.get("uri"),
        }


class Colab(gcp_v2.Resource):
    def _request(self):
        return {
            "customEnvironmentSpec": gcp_v2.remove_empties(
                CustomEnvironmentSpec(self.request.get("custom_environment_spec", {})).to_request()
            ),  # remove empty values
            "dataformRepositorySource": gcp_v2.remove_empties(
                DataformRepositorySource(self.request.get("dataform_repository_source", {})).to_request()
            ),  # remove empty values
            "directNotebookSource": gcp_v2.remove_empties(
                DirectNotebookSource(self.request.get("direct_notebook_source", {})).to_request()
            ),  # remove empty values
            "displayName": self.request.get("display_name"),
            "executionTimeout": self.request.get("execution_timeout"),
            "executionUser": self.request.get("execution_user"),
            "gcsNotebookSource": gcp_v2.remove_empties(
                GcsNotebookSource(self.request.get("gcs_notebook_source", {})).to_request()
            ),  # remove empty values
            "gcsOutputUri": self.request.get("gcs_output_uri"),
            "notebookRuntimeTemplateResourceName": self.request.get("notebook_runtime_template_resource_name"),
            "serviceAccount": self.request.get("service_account"),
        }

    def _response(self):
        return {
            "customEnvironmentSpec": CustomEnvironmentSpec().from_response(
                self.response.get("customEnvironmentSpec", {})
            ),
            "dataformRepositorySource": DataformRepositorySource().from_response(
                self.response.get("dataformRepositorySource", {})
            ),
            "directNotebookSource": DirectNotebookSource().from_response(self.response.get("directNotebookSource", {})),
            "displayName": self.response.get("displayName"),
            "executionTimeout": self.response.get("executionTimeout"),
            "executionUser": self.response.get("executionUser"),
            "gcsNotebookSource": GcsNotebookSource().from_response(self.response.get("gcsNotebookSource", {})),
            "gcsOutputUri": self.response.get("gcsOutputUri"),
            "notebookRuntimeTemplateResourceName": self.response.get("notebookRuntimeTemplateResourceName"),
            "serviceAccount": self.response.get("serviceAccount"),
        }


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            custom_environment_spec=dict(
                type="dict",
                options=dict(
                    machine_spec=dict(
                        type="dict",
                        options=dict(
                            accelerator_count=dict(
                                type="int",
                            ),
                            accelerator_type=dict(
                                type="str",
                            ),
                            machine_type=dict(
                                type="str",
                            ),
                        ),
                    ),
                    network_spec=dict(
                        type="dict",
                        options=dict(
                            enable_internet_access=dict(
                                type="bool",
                            ),
                            network=dict(
                                type="str",
                            ),
                            subnetwork=dict(
                                type="str",
                            ),
                        ),
                    ),
                    persistent_disk_spec=dict(
                        type="dict",
                        options=dict(
                            disk_size_gb=dict(
                                type="str",
                            ),
                            disk_type=dict(
                                type="str",
                            ),
                        ),
                    ),
                ),
            ),
            dataform_repository_source=dict(
                type="dict",
                options=dict(
                    commit_sha=dict(
                        type="str",
                    ),
                    dataform_repository_resource_name=dict(
                        type="str",
                        required=True,
                    ),
                ),
            ),
            direct_notebook_source=dict(
                type="dict",
                options=dict(
                    content=dict(
                        type="str",
                        required=True,
                    )
                ),
            ),
            display_name=dict(
                type="str",
                required=True,
            ),
            execution_timeout=dict(
                type="str",
            ),
            execution_user=dict(
                type="str",
            ),
            gcs_notebook_source=dict(
                type="dict",
                options=dict(
                    generation=dict(
                        type="str",
                    ),
                    uri=dict(
                        type="str",
                        required=True,
                    ),
                ),
            ),
            gcs_output_uri=dict(
                type="str",
                required=True,
            ),
            location=dict(
                type="str",
                required=True,
            ),
            notebook_execution_job_id=dict(
                type="str",
            ),
            notebook_runtime_template_resource_name=dict(
                type="str",
            ),
            service_account=dict(
                type="str",
            ),
        ),
        mutually_exclusive=[
            ["custom_environment_spec", "notebook_runtime_template_resource_name"],
            ["dataform_repository_source", "direct_notebook_source", "gcs_notebook_source"],
            ["execution_user", "service_account"],
        ],
        required_one_of=[
            ["custom_environment_spec", "notebook_runtime_template_resource_name"],
            ["dataform_repository_source", "direct_notebook_source", "gcs_notebook_source"],
            ["execution_user", "service_account"],
        ],
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{location}-aiplatform.googleapis.com/v1/",
        base_uri="projects/{project}/locations/{location}/notebookExecutionJobs",
        configs={
            "create": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookExecutionJobs?notebook_execution_job_id={notebook_execution_job_id}",
                    "async_uri": "{op_id}",
                    "verb": "POST",
                    "timeout_minutes": 20,
                }
            ),
            "delete": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookExecutionJobs/{notebook_execution_job_id}",
                    "async_uri": "{op_id}",
                    "verb": "DELETE",
                    "timeout_minutes": 20,
                }
            ),
            "read": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookExecutionJobs/{notebook_execution_job_id}",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "update": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/notebookExecutionJobs/{notebook_execution_job_id}",
                    "async_uri": "{op_id}",
                    "verb": "PUT",
                    "timeout_minutes": 20,
                }
            ),
        },
    )

    request = gcp_v2.remove_nones(module.params)
    resource = Colab(request, module=module, product="Colab", kind="colab#notebookExecution", op_configs=op_configs)

    resource._state = state  # store the state in the resource object

    # Set this variable in one of the pre steps to implement custom diff logic
    custom_diff = None

    # BEGIN massaging ResourceRef properties
    # END massaging ResourceRef properties

    read_link: str = ""  # give it a chance for pre-read to overload

    # --------- BEGIN pre-read custom code ---------
    # for this module, we're hitting the list endpoint and filtering on display name
    read_link = resource.build_link("list") + "?filter=displayName=" + request.get("display_name")

    # --------- END pre-read custom code ---------

    if read_link == "":
        read_link = resource.build_link("read")
    existing_obj = resource.from_response(resource.get(read_link, allow_not_found=True) or {})
    new_obj = {}
    gcp_v2.debug(module, request=gcp_v2.remove_empties(resource.to_request()), existing=existing_obj, post=False)

    # --------- BEGIN post-read custom code ---------
    # if there are existing notebook executions, the call would have returned a list
    if not gcp_v2.empty(existing_obj):
        for nb in existing_obj.get("notebookExecutionJobs", []):
            if nb.get("displayName") == request.get("display_name"):
                existing_obj = nb
                break

    # --------- END post-read custom code ---------

    if custom_diff is not None:
        is_different = custom_diff
    else:
        is_different = resource.diff(gcp_v2.remove_empties(existing_obj))

    gcp_v2.debug(
        module,
        request=gcp_v2.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp_v2.empty(existing_obj):
        if state == "present":
            gcp_v2.debug(module, action="create")
            try:
                # --------- BEGIN create code ---------
                create_link: str = ""  # give it a chance for pre-create to overload
                # --------- BEGIN pre-create custom code ---------
                # if not provided, blank the notebook execution job id
                resource.url_params["notebook_execution_job_id"] = request.get("notebook_execution_job_id", "")

                # --------- END pre-create custom code ---------
                if create_link == "":
                    create_link = resource.build_link("create")
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                create_async_uri = op_configs.create.async_uri
                create_async_func = getattr(resource, op_configs.create.verb + "_async")
                gcp_v2.debug(module, msg="Creating resource", create_link=create_link, async_uri=create_async_uri)

                if create_async_uri != "":
                    new_obj = create_async_func(create_link, async_uri=create_async_uri, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.with_kind(resource.from_response(new_obj))
                gcp_v2.debug(module, new=new_obj, action="create", post=False)
                gcp_v2.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            gcp_v2.debug(module, action="delete")
            try:
                # --------- BEGIN delete code ---------
                delete_link: str = ""  # give it a chance for pre-delete to overload
                # --------- BEGIN pre-delete custom code ---------
                # need to set required parameter "notebook_execution_job_id" from existing resource name
                resource.url_params["notebook_execution_job_id"] = existing_obj["name"].split("/")[-1]

                # --------- END pre-delete custom code ---------
                if delete_link == "":
                    delete_link = resource.build_link("delete")
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                delete_async_uri = op_configs.delete.async_uri
                delete_async_func = getattr(resource, op_configs.delete.verb + "_async")
                gcp_v2.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_uri=delete_async_uri,
                )

                if delete_async_uri != "":
                    new_obj = delete_async_func(delete_link, async_uri=delete_async_uri, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.from_response(new_obj)
                gcp_v2.debug(module, new=new_obj, action="delete", post=False)
                gcp_v2.debug(module, new=new_obj, action="delete", post=True)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                gcp_v2.debug(module, action="update")
                try:
                    # --------- BEGIN custom update code ---------
                    raise Exception("Updating a notebook execution is not supported")
                    # --------- END custom update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj.update({"changed": changed})
    gcp_v2.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
