#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - Vertex AI Feature Group.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_vertexai_feature_group
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featureGroups)'
  - 'Creating a Feature Group Guide: U(https://cloud.google.com/vertex-ai/docs/featurestore/latest/create-featuregroup)'
options:
  big_query:
    description:
      - Indicates that features for this group come from BigQuery Table/View.
      - By default treats the source as a sparse time series source, which is required to have an entityId and a feature_timestamp column in the source.
    suboptions:
      big_query_source:
        description:
          - The BigQuery source URI that points to either a BigQuery Table or View.
          - This property is immutable, to change it, you must delete and recreate the resource.
        required: true
        suboptions:
          input_uri:
            description:
              - BigQuery URI to a table, up to 2000 characters long.
              - 'For example: `bq://projectId.bqDatasetId.bqTableId.`.'
            required: true
            type: str
        type: dict
      entity_id_columns:
        description:
          - Columns to construct entityId / row keys.
          - If not provided defaults to entityId.
        elements: str
        type: list
    type: dict
  description:
    description:
      - The description of the FeatureGroup.
    type: str
  labels:
    description:
      - The labels with user-defined metadata to organize your FeatureGroup.
      - '**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.'
    type: dict
  name:
    description:
      - The resource name of the Feature Group.
    type: str
  region:
    description:
      - The region of feature group.
      - eg us-central1.
      - This property is immutable, to change it, you must delete and recreate the resource.
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist in GCP.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Creates a GCP VertexAI.FeatureGroup resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create feature group
  google.cloud.gcp_vertexai_feature_group:
    state: present
    name: my_feature_group
    description: "My feature group"
    region: us-central1
    big_query:
      big_query_source:
        input_uri: "bq://{{ gcp_project }}.my_dataset.my_table"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
createTime:
  description:
    - The timestamp of when the FeatureGroup was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
  returned: success
  type: str
state:
  description: The current state of the resource.
  returned: always
  type: str
updateTime:
  description:
    - The timestamp of when the FeatureGroup was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
  returned: success
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

# BEGIN Custom imports
import copy

# END Custom imports


class BigQuery(gcp_v2.Resource):
    def _request(self):
        return {
            "bigQuerySource": gcp_v2.remove_empties(
                BigQueryBigQuerySource(self.request.get("big_query_source", {})).to_request()
            ),  # remove empty values
            "entityIdColumns": self.request.get("entity_id_columns"),
        }


class BigQueryBigQuerySource(gcp_v2.Resource):
    def _request(self):
        return {
            "inputUri": self.request.get("input_uri"),
        }


class VertexAI(gcp_v2.Resource):
    def _request(self):
        return {
            "bigQuery": gcp_v2.remove_empties(
                BigQuery(self.request.get("big_query", {})).to_request()
            ),  # remove empty values
            "description": self.request.get("description"),
            "labels": self.request.get("labels"),
            "name": self.request.get("name"),
        }

    def _response(self):
        return {
            "createTime": self.response.get("createTime"),
            "etag": self.response.get("etag"),
            "updateTime": self.response.get("updateTime"),
        }

    def decode(self, response):
        "Custom decoder function, mutates the response object before it is returned to the module caller."

        # --------- BEGIN custom decoder code ---------
        r = copy.deepcopy(response)
        if "name" in r:
            r["name"] = r.pop("name").split("/")[-1]
        return r

        # --------- END custom decoder code ---------


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            name=dict(
                type="str",
            ),
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            big_query=dict(
                type="dict",
                options=dict(
                    big_query_source=dict(
                        type="dict",
                        required=True,
                        options=dict(
                            input_uri=dict(
                                type="str",
                                required=True,
                            )
                        ),
                    ),
                    entity_id_columns=dict(
                        type="list",
                        elements="str",
                    ),
                ),
            ),
            description=dict(
                type="str",
            ),
            labels=dict(
                type="dict",
            ),
            region=dict(
                type="str",
            ),
        )
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{region}-aiplatform.googleapis.com/v1/",
        base_uri="projects/{project}/locations/{region}/featureGroups",
        configs={
            "create": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/featureGroups?featureGroupId={name}",
                    "async_uri": "{op_id}",
                    "verb": "POST",
                    "timeout_minutes": 20,
                }
            ),
            "delete": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/featureGroups/{name}",
                    "async_uri": "{op_id}",
                    "verb": "DELETE",
                    "timeout_minutes": 20,
                }
            ),
            "read": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/featureGroups/{name}",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "update": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/featureGroups/{name}",
                    "async_uri": "{op_id}",
                    "verb": "PATCH",
                    "timeout_minutes": 20,
                }
            ),
        },
    )

    request = gcp_v2.remove_nones(module.params)
    resource = VertexAI(request, module=module, product="VertexAI", kind="vertexai#featureGroup", op_configs=op_configs)

    resource._state = state  # store the state in the resource object

    # Set this variable in one of the pre steps to implement custom diff logic
    custom_diff = None

    # BEGIN massaging ResourceRef properties
    # END massaging ResourceRef properties

    read_link: str = ""  # give it a chance for pre-read to overload

    if read_link == "":
        read_link = resource.build_link("read")
    existing_obj = resource.from_response(resource.get(read_link, allow_not_found=True) or {})
    new_obj = {}
    gcp_v2.debug(module, request=gcp_v2.remove_empties(resource.to_request()), existing=existing_obj, post=False)

    if custom_diff is not None:
        is_different = custom_diff
    else:
        is_different = resource.diff(gcp_v2.remove_empties(existing_obj))

    gcp_v2.debug(
        module,
        request=gcp_v2.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp_v2.empty(existing_obj):
        if state == "present":
            gcp_v2.debug(module, action="create")
            try:
                # --------- BEGIN create code ---------
                create_link: str = ""  # give it a chance for pre-create to overload
                if create_link == "":
                    create_link = resource.build_link("create")
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                create_async_uri = op_configs.create.async_uri
                create_async_func = getattr(resource, op_configs.create.verb + "_async")
                gcp_v2.debug(module, msg="Creating resource", create_link=create_link, async_uri=create_async_uri)

                if create_async_uri != "":
                    new_obj = create_async_func(create_link, async_uri=create_async_uri, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.with_kind(resource.from_response(new_obj))
                gcp_v2.debug(module, new=new_obj, action="create", post=False)
                gcp_v2.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            gcp_v2.debug(module, action="delete")
            try:
                # --------- BEGIN delete code ---------
                delete_link: str = ""  # give it a chance for pre-delete to overload
                if delete_link == "":
                    delete_link = resource.build_link("delete")
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                delete_async_uri = op_configs.delete.async_uri
                delete_async_func = getattr(resource, op_configs.delete.verb + "_async")
                gcp_v2.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_uri=delete_async_uri,
                )

                if delete_async_uri != "":
                    new_obj = delete_async_func(delete_link, async_uri=delete_async_uri, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.from_response(new_obj)
                gcp_v2.debug(module, new=new_obj, action="delete", post=False)
                gcp_v2.debug(module, new=new_obj, action="delete", post=True)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                gcp_v2.debug(module, action="update")
                try:
                    # --------- BEGIN update code ---------
                    update_link: str = ""  # give it a chance for pre-update to overload
                    if update_link == "":
                        update_link = resource.build_link("update")
                    update_retries = op_configs.update.timeout
                    update_func = getattr(resource, op_configs.update.verb)
                    update_async_uri = op_configs.update.async_uri
                    update_async_func = getattr(resource, op_configs.update.verb + "_async")
                    gcp_v2.debug(
                        module,
                        msg="Updating resource",
                        update_link=update_link,
                        async_uri=update_async_uri,
                    )
                    if update_async_uri != "":
                        new_obj = update_async_func(update_link, async_uri=update_async_uri, retries=update_retries)
                    else:
                        new_obj = update_func(update_link)
                    new_obj = resource.with_kind(resource.from_response(new_obj))
                    gcp_v2.debug(module, new=new_obj, action="update", post=False)
                    gcp_v2.debug(module, new=new_obj, action="update", post=True)
                    # --------- END update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj.update({"changed": changed})
    gcp_v2.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
