#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - A policy for container image binary authorization.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_binaryauthorization_policy
notes:
  - 'API Reference: U(https://cloud.google.com/binary-authorization/docs/reference/rest/)'
  - 'Official Documentation Guide: U(https://cloud.google.com/binary-authorization/)'
options:
  admission_whitelist_patterns:
    description:
      - A whitelist of image patterns to exclude from admission rules.
      - If an image's name matches a whitelist pattern, the image's admission requests will always be permitted regardless of your admission rules.
    elements: dict
    suboptions:
      name_pattern:
        description:
          - An image name pattern to whitelist, in the form `registry/path/to/image`.
          - This supports a trailing * as a wildcard, but this is allowed only in text after the registry/ part.
        required: true
        type: str
    type: list
  cluster_admission_rules:
    description:
      - Per-cluster admission rules.
      - An admission rule specifies either that all container images used in a pod creation request must be attested to by one or more attestors, that all pod creations will be allowed, or that all pod creations will be denied.
      - There can be at most one admission rule per cluster spec.
      - 'Identifier format: `{{location}}.{{clusterId}}`.'
      - A location is either a compute zone (e.g.
      - '`us-central1-a`) or a region (e.g.'
      - '`us-central1`).'
    elements: dict
    suboptions:
      cluster:
        description:
          - The identifier for this cluster_admission_rules entry, used as the map key.
        required: true
        type: str
      enforcement_mode:
        choices:
          - ENFORCED_BLOCK_AND_AUDIT_LOG
          - DRYRUN_AUDIT_LOG_ONLY
        description:
          - The action when a pod creation is denied by the admission rule.
        required: true
        type: str
      evaluation_mode:
        choices:
          - ALWAYS_ALLOW
          - REQUIRE_ATTESTATION
          - ALWAYS_DENY
        description:
          - How this admission rule will be evaluated.
        required: true
        type: str
      require_attestations_by:
        description:
          - The resource names of the attestors that must attest to a container image.
          - If the attestor is in a different project from the policy, it should be specified in the format `projects/*/attestors/*`.
          - Each attestor must exist before a policy can reference it.
          - To add an attestor to a policy the principal issuing the policy change request must be able to read the attestor resource.
          - 'Note: this field must be non-empty when the evaluation_mode field specifies REQUIRE_ATTESTATION, otherwise it must be empty.'
        elements: str
        type: list
    type: list
  default_admission_rule:
    description:
      - Default admission rule for a cluster without a per-cluster admission rule.
    required: true
    suboptions:
      enforcement_mode:
        choices:
          - ENFORCED_BLOCK_AND_AUDIT_LOG
          - DRYRUN_AUDIT_LOG_ONLY
        description:
          - The action when a pod creation is denied by the admission rule.
        required: true
        type: str
      evaluation_mode:
        choices:
          - ALWAYS_ALLOW
          - REQUIRE_ATTESTATION
          - ALWAYS_DENY
        description:
          - How this admission rule will be evaluated.
        required: true
        type: str
      require_attestations_by:
        description:
          - The resource names of the attestors that must attest to a container image.
          - If the attestor is in a different project from the policy, it should be specified in the format `projects/*/attestors/*`.
          - Each attestor must exist before a policy can reference it.
          - To add an attestor to a policy the principal issuing the policy change request must be able to read the attestor resource.
          - 'Note: this field must be non-empty when the evaluation_mode field specifies REQUIRE_ATTESTATION, otherwise it must be empty.'
        elements: str
        type: list
    type: dict
  description:
    description:
      - A descriptive comment.
    type: str
  global_policy_evaluation_mode:
    choices:
      - ENABLE
      - DISABLE
    description:
      - Controls the evaluation of a Google-maintained global admission policy for common system-level images.
      - Images not covered by the global policy will be subject to the project admission policy.
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Manages a BinaryAuthorization.Policy resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create Custom Policy
  google.cloud.gcp_binaryauthorization_policy:
    state: present
    admission_whitelist_patterns:
      - name_pattern: "gcr.io/google_containers/*"
    default_admission_rule:
      evaluation_mode: ALWAYS_ALLOW
      enforcement_mode: ENFORCED_BLOCK_AND_AUDIT_LOG
    cluster_admission_rules:  # enforce attestations in a given cluster
      - cluster: us-central1-a.my-cluster
        evaluation_mode: REQUIRE_ATTESTATION
        enforcement_mode: ENFORCED_BLOCK_AND_AUDIT_LOG
        require_attestations_by:
          - projects/my-project/attestors/attestor-1
          - projects/my-project/attestors/attestor-2

################################################################################

- name: Delete Custom Policy (reset to default)
  google.cloud.gcp_binaryauthorization_policy:
    state: absent
    default_admission_rule:
      evaluation_mode: ALWAYS_ALLOW
      enforcement_mode: ENFORCED_BLOCK_AND_AUDIT_LOG
"""  # noqa: E501

RETURN = r"""
admissionWhitelistPatterns:
  contains:
    namePattern:
      description:
        - An image name pattern to whitelist, in the form `registry/path/to/image`.
        - This supports a trailing * as a wildcard, but this is allowed only in text after the registry/ part.
      returned: always
      type: str
  description:
    - A whitelist of image patterns to exclude from admission rules.
    - If an image's name matches a whitelist pattern, the image's admission requests will always be permitted regardless of your admission rules.
  elements: dict
  returned: when set
  type: list
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
clusterAdmissionRules:
  contains:
    cluster:
      description:
        - The identifier for this ClusterAdmissionRules entry, used as the map key.
      returned: success
      type: str
    enforcementMode:
      description:
        - The action when a pod creation is denied by the admission rule.
      returned: always
      type: str
    evaluationMode:
      description:
        - How this admission rule will be evaluated.
      returned: always
      type: str
    requireAttestationsBy:
      description:
        - The resource names of the attestors that must attest to a container image.
        - If the attestor is in a different project from the policy, it should be specified in the format `projects/*/attestors/*`.
        - Each attestor must exist before a policy can reference it.
        - To add an attestor to a policy the principal issuing the policy change request must be able to read the attestor resource.
        - 'Note: this field must be non-empty when the evaluation_mode field specifies REQUIRE_ATTESTATION, otherwise it must be empty.'
      elements: str
      returned: when set
      type: list
  description:
    - Per-cluster admission rules.
    - An admission rule specifies either that all container images used in a pod creation request must be attested to by one or more attestors, that all pod creations will be allowed, or that all pod creations will be denied.
    - There can be at most one admission rule per cluster spec.
    - 'Identifier format: `{{location}}.{{clusterId}}`.'
    - A location is either a compute zone (e.g.
    - '`us-central1-a`) or a region (e.g.'
    - '`us-central1`).'
  elements: dict
  returned: when set
  type: list
defaultAdmissionRule:
  contains:
    enforcementMode:
      description:
        - The action when a pod creation is denied by the admission rule.
      returned: always
      type: str
    evaluationMode:
      description:
        - How this admission rule will be evaluated.
      returned: always
      type: str
    requireAttestationsBy:
      description:
        - The resource names of the attestors that must attest to a container image.
        - If the attestor is in a different project from the policy, it should be specified in the format `projects/*/attestors/*`.
        - Each attestor must exist before a policy can reference it.
        - To add an attestor to a policy the principal issuing the policy change request must be able to read the attestor resource.
        - 'Note: this field must be non-empty when the evaluation_mode field specifies REQUIRE_ATTESTATION, otherwise it must be empty.'
      elements: str
      returned: when set
      type: list
  description:
    - Default admission rule for a cluster without a per-cluster admission rule.
  returned: always
  type: dict
description:
  description:
    - A descriptive comment.
  returned: when set
  type: str
globalPolicyEvaluationMode:
  description:
    - Controls the evaluation of a Google-maintained global admission policy for common system-level images.
    - Images not covered by the global policy will be subject to the project admission policy.
  returned: when set
  type: str
state:
  description: The current state of the resource.
  returned: always
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

# BEGIN Custom imports
# END Custom imports


class AdmissionWhitelistPatterns(gcp_v2.Resource):
    def _request(self):
        return {
            "namePattern": self.request.get("name_pattern"),
        }


class ClusterAdmissionRules(gcp_v2.Resource):
    def _request(self):
        return {
            "enforcementMode": self.request.get("enforcement_mode"),
            "evaluationMode": self.request.get("evaluation_mode"),
            "requireAttestationsBy": self.request.get("require_attestations_by"),
        }


class DefaultAdmissionRule(gcp_v2.Resource):
    def _request(self):
        return {
            "enforcementMode": self.request.get("enforcement_mode"),
            "evaluationMode": self.request.get("evaluation_mode"),
            "requireAttestationsBy": self.request.get("require_attestations_by"),
        }


class BinaryAuthorization(gcp_v2.Resource):
    def _request(self):
        return {
            "admissionWhitelistPatterns": [
                AdmissionWhitelistPatterns(item).to_request()
                for item in (self.request.get("admission_whitelist_patterns") or [])
            ],
            "clusterAdmissionRules": {
                item["cluster"]: gcp_v2.remove_empties(ClusterAdmissionRules(item).to_request())
                for item in (self.request.get("cluster_admission_rules") or [])
            },
            "defaultAdmissionRule": gcp_v2.remove_empties(
                DefaultAdmissionRule(self.request.get("default_admission_rule", {})).to_request()
            ),  # remove empty values
            "description": self.request.get("description"),
            "globalPolicyEvaluationMode": self.request.get("global_policy_evaluation_mode"),
        }

    def _response(self):
        return {}

    def decode(self, response):
        "Custom decoder function, mutates the response object before it is returned to the module caller."

        # --------- BEGIN custom decoder code ---------
        # flatten name
        if not gcp_v2.empty(response):
            n: str = response.pop("name")
            response["name"] = gcp_v2.flatten_name(n)
            response["id"] = n

        return response

        # --------- END custom decoder code ---------


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            admission_whitelist_patterns=dict(
                type="list",
                elements="dict",
                options=dict(
                    name_pattern=dict(
                        type="str",
                        required=True,
                    )
                ),
            ),
            cluster_admission_rules=dict(
                type="list",
                elements="dict",
                options=dict(
                    cluster=dict(
                        type="str",
                        required=True,
                    ),
                    enforcement_mode=dict(
                        type="str",
                        required=True,
                        choices=["ENFORCED_BLOCK_AND_AUDIT_LOG", "DRYRUN_AUDIT_LOG_ONLY"],
                    ),
                    evaluation_mode=dict(
                        type="str",
                        required=True,
                        choices=["ALWAYS_ALLOW", "REQUIRE_ATTESTATION", "ALWAYS_DENY"],
                    ),
                    require_attestations_by=dict(
                        type="list",
                        elements="str",
                    ),
                ),
            ),
            default_admission_rule=dict(
                type="dict",
                required=True,
                options=dict(
                    enforcement_mode=dict(
                        type="str",
                        required=True,
                        choices=["ENFORCED_BLOCK_AND_AUDIT_LOG", "DRYRUN_AUDIT_LOG_ONLY"],
                    ),
                    evaluation_mode=dict(
                        type="str",
                        required=True,
                        choices=["ALWAYS_ALLOW", "REQUIRE_ATTESTATION", "ALWAYS_DENY"],
                    ),
                    require_attestations_by=dict(
                        type="list",
                        elements="str",
                    ),
                ),
            ),
            description=dict(
                type="str",
            ),
            global_policy_evaluation_mode=dict(
                type="str",
                choices=["ENABLE", "DISABLE"],
            ),
        )
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://binaryauthorization.googleapis.com/v1/",
        base_uri="projects/{project}/policy",
        configs={
            "create": gcp_v2.ResourceOpConfig(
                **{"uri": "projects/{project}/policy", "async_uri": "", "verb": "PUT", "timeout_minutes": 20}
            ),
            "delete": gcp_v2.ResourceOpConfig(
                **{"uri": "projects/{project}/policy", "async_uri": "", "verb": "PUT", "timeout_minutes": 20}
            ),
            "read": gcp_v2.ResourceOpConfig(
                **{"uri": "projects/{project}/policy", "async_uri": "", "verb": "GET", "timeout_minutes": 0}
            ),
            "update": gcp_v2.ResourceOpConfig(
                **{"uri": "projects/{project}/policy", "async_uri": "", "verb": "PUT", "timeout_minutes": 20}
            ),
        },
    )

    request = gcp_v2.remove_nones(module.params)
    resource = BinaryAuthorization(
        request, module=module, product="BinaryAuthorization", kind="binaryauthorization#policy", op_configs=op_configs
    )

    resource._state = state  # store the state in the resource object

    # Set this variable in one of the pre steps to implement custom diff logic
    custom_diff = False

    # BEGIN massaging ResourceRef properties
    # END massaging ResourceRef properties

    read_link: str = ""  # give it a chance for pre-read to overload

    if read_link == "":
        read_link = resource.build_link("read")
    existing_obj = resource.from_response(resource.get(read_link, allow_not_found=True) or {})
    new_obj = {}
    gcp_v2.debug(module, request=gcp_v2.remove_empties(resource.to_request()), existing=existing_obj, post=False)

    is_different = custom_diff or resource.diff(gcp_v2.remove_empties(existing_obj))

    gcp_v2.debug(
        module,
        request=gcp_v2.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp_v2.empty(existing_obj):
        if state == "present":
            gcp_v2.debug(module, action="create")
            try:
                # --------- BEGIN create code ---------
                create_link: str = ""  # give it a chance for pre-create to overload
                if create_link == "":
                    create_link = resource.build_link("create")
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                create_async_uri = op_configs.create.async_uri
                create_async_func = getattr(resource, op_configs.create.verb + "_async")
                gcp_v2.debug(module, msg="Creating resource", create_link=create_link, async_uri=create_async_uri)

                if create_async_uri != "":
                    new_obj = create_async_func(create_link, async_uri=create_async_uri, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.with_kind(resource.from_response(new_obj))
                gcp_v2.debug(module, new=new_obj, action="create", post=False)
                gcp_v2.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            gcp_v2.debug(module, action="delete")
            try:
                # --------- BEGIN delete code ---------
                delete_link: str = ""  # give it a chance for pre-delete to overload
                # --------- BEGIN pre-delete custom code ---------
                # when you delete, you actually reset it back to defaults
                resource.request = {
                    "global_policy_evaluation_mode": "ENABLE",
                    "default_admission_rule": {
                        "evaluation_mode": "ALWAYS_ALLOW",
                        "enforcement_mode": "ENFORCED_BLOCK_AND_AUDIT_LOG",
                    },
                }

                # --------- END pre-delete custom code ---------
                if delete_link == "":
                    delete_link = resource.build_link("delete")
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                delete_async_uri = op_configs.delete.async_uri
                delete_async_func = getattr(resource, op_configs.delete.verb + "_async")
                gcp_v2.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_uri=delete_async_uri,
                )

                if delete_async_uri != "":
                    new_obj = delete_async_func(delete_link, async_uri=delete_async_uri, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.from_response(new_obj)
                gcp_v2.debug(module, new=new_obj, action="delete", post=False)
                gcp_v2.debug(module, new=new_obj, action="delete", post=True)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                gcp_v2.debug(module, action="update")
                try:
                    # --------- BEGIN update code ---------
                    update_link: str = ""  # give it a chance for pre-update to overload
                    if update_link == "":
                        update_link = resource.build_link("update")
                    update_retries = op_configs.update.timeout
                    update_func = getattr(resource, op_configs.update.verb)
                    update_async_uri = op_configs.update.async_uri
                    update_async_func = getattr(resource, op_configs.update.verb + "_async")
                    gcp_v2.debug(
                        module,
                        msg="Updating resource",
                        update_link=update_link,
                        async_uri=update_async_uri,
                    )
                    if update_async_uri != "":
                        new_obj = update_async_func(update_link, async_uri=update_async_uri, retries=update_retries)
                    else:
                        new_obj = update_func(update_link)
                    new_obj = resource.with_kind(resource.from_response(new_obj))
                    gcp_v2.debug(module, new=new_obj, action="update", post=False)
                    gcp_v2.debug(module, new=new_obj, action="update", post=True)
                    # --------- END update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj = gcp_v2.filter_reserved_keys(new_obj)
    new_obj.update({"changed": changed})
    gcp_v2.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
