#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - Feature Metadata information that describes an attribute of an entity type. For example, apple is an entity type, and color is a feature that describes apple.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_vertexai_featurestore_entitytype_feature_info
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featurestores.entityTypes.features)'
  - 'Official Documentation Guide: U(https://cloud.google.com/vertex-ai/docs)'
options:
  entitytype:
    description:
      - The name of the Featurestore to use, in the format projects/{project}/locations/{location}/featurestores/{featurestore}/entityTypes/{entitytype}.
    required: true
    type: str
  filters:
    description:
      - A list of filter expression strings used to filter the resources returned by the API.
      - Each string is a filter expression (e.g. C(some_field = "SOME_VALUE")).
      - Multiple expressions are combined with a logical AND.
      - Refer to the filter topic documentation U(https://cloud.google.com/sdk/gcloud/reference/topic/filters).
      - Refer to the IAP-160 filter syntax documentation U(https://google.aip.dev/160).
    elements: str
    type: list
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: List GCP vertexai.FeaturestoreEntitytypeFeature resources
"""  # noqa: E501

EXAMPLES = r"""
- name: List all gcp_vertexai_featurestore_entitytype_feature_info resources
  google.cloud.gcp_vertexai_featurestore_entitytype_feature_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result

- name: List gcp_vertexai_featurestore_entitytype_feature_info resources matching given filters
  google.cloud.gcp_vertexai_featurestore_entitytype_feature_info:
    filters:
      - display_name = "my-resource"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether any changes were made (always false for info modules).
  returned: always
  type: bool
resources:
  contains:
    createTime:
      description:
        - The timestamp of when the entity type was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
      returned: success
      type: str
    description:
      description:
        - Description of the feature.
      returned: when set
      type: str
    labels:
      description:
        - A set of key/value label pairs to assign to the feature.
        - '**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.'
      returned: when set
      type: dict
    updateTime:
      description:
        - The timestamp when the entity type was most recently updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
      returned: success
      type: str
    valueType:
      description:
        - Type of Feature value.
        - Immutable.
        - https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.featurestores.entityTypes.features#ValueType.
      returned: always
      type: str
  description: List of VertexAI.FeaturestoreEntitytypeFeature resources matching the supplied filters. May be empty, contain a single resource, or multiple resources.
  elements: dict
  returned: always
  type: list
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

# BEGIN Custom imports
import re

# END Custom imports

################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            entitytype=dict(
                type="str",
                required=True,
            ),
            filters=dict(
                type="list",
                elements="str",
            ),
        ),
        supports_check_mode=True,
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    # info modules only require the "collection" url
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{region}-aiplatform.googleapis.com/v1/", base_uri="{entitytype}/features", configs={}
    )

    info = gcp_v2.Resource(
        module.params,  # only need it to build the link
        module=module,
        product="VertexAI",
        kind="vertexai#featurestoreEntitytypeFeature",
        op_configs=op_configs,
    )

    filter_exprs = module.params.get("filters") or []

    # BEGIN pre_read custom code
    # extract region from entitytype
    pattern = r"projects/(.+)/locations/(.+)/featurestores/(.+)/entityTypes/(.+)"
    match = re.search(pattern, str(module.params.get("entitytype")))
    if match:
        info.url_params["region"] = match.group(2)

    # END pre_read custom code

    link = info.build_link("list")
    resources = info.list(link, key="features", filters=filter_exprs)

    module.exit_json(changed=False, resources=resources)


if __name__ == "__main__":
    main()
