#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - A representation of a collection of database items organized in a way that allows for approximate nearest neighbor (a.k.a ANN) algorithms search.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_vertexai_index_info
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.indexes/)'
options:
  filters:
    description:
      - A list of filter expression strings used to filter the resources returned by the API.
      - Each string is a filter expression (e.g. C(some_field = "SOME_VALUE")).
      - Multiple expressions are combined with a logical AND.
      - Refer to the filter topic documentation U(https://cloud.google.com/sdk/gcloud/reference/topic/filters).
      - Refer to the IAP-160 filter syntax documentation U(https://google.aip.dev/160).
    elements: str
    type: list
  region:
    description:
      - The region of the index.
      - eg us-central1.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: List GCP vertexai.Index resources
"""  # noqa: E501

EXAMPLES = r"""
- name: List all gcp_vertexai_index_info resources
  google.cloud.gcp_vertexai_index_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result

- name: List gcp_vertexai_index_info resources matching given filters
  google.cloud.gcp_vertexai_index_info:
    filters:
      - display_name = "my-resource"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether any changes were made (always false for info modules).
  returned: always
  type: bool
resources:
  contains:
    createTime:
      description:
        - The timestamp of when the Index was created in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
      returned: success
      type: str
    deployedIndexes:
      contains:
        deployedIndexId:
          description:
            - The ID of the DeployedIndex in the above IndexEndpoint.
          returned: success
          type: str
        indexEndpoint:
          description:
            - A resource name of the IndexEndpoint.
          returned: success
          type: str
      description:
        - The pointers to DeployedIndexes created from this Index.
        - An Index can be only deleted if all its DeployedIndexes had been undeployed first.
      elements: dict
      returned: success
      type: list
    description:
      description:
        - The description of the Index.
      returned: when set
      type: str
    displayName:
      description:
        - The display name of the Index.
        - The name can be up to 128 characters long and can consist of any UTF-8 characters.
      returned: always
      type: str
    encryptionSpec:
      contains:
        kmsKeyName:
          description:
            - The Cloud KMS resource identifier of the customer managed encryption key used to protect a resource.
            - 'Has the form: `projects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key`.'
            - The key needs to be in the same region as where the compute resource is created.
          returned: always
          type: str
      description:
        - Customer-managed encryption key spec for an Index.
        - If set, this Index and all sub-resources of this Index will be secured by this key.
      returned: when set
      type: dict
    indexStats:
      contains:
        shardsCount:
          description:
            - The number of shards in the Index.
          returned: success
          type: int
        vectorsCount:
          description:
            - The number of vectors in the Index.
          returned: success
          type: str
      description:
        - Stats of the index resource.
      returned: success
      type: dict
    indexUpdateMethod:
      description:
        - The update method to use with this Index.
        - The value must be the followings.
        - If not set, BATCH_UPDATE will be used by default.
        - '* BATCH_UPDATE: user can call indexes.patch with files on Cloud Storage of datapoints to update.'
        - '* STREAM_UPDATE: user can call indexes.upsertDatapoints/DeleteDatapoints to update the Index and the updates will be applied in corresponding DeployedIndexes in nearly real-time.'
      returned: when set
      type: str
    labels:
      description:
        - The labels with user-defined metadata to organize your Indexes.
        - '**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.'
      returned: when set
      type: dict
    metadata:
      contains:
        config:
          contains:
            algorithmConfig:
              contains:
                bruteForceConfig:
                  description:
                    - Configuration options for using brute force search, which simply implements the standard linear search in the database for each query.
                  returned: when set
                  type: dict
                treeAhConfig:
                  contains:
                    leafNodeEmbeddingCount:
                      description:
                        - Number of embeddings on each leaf node.
                        - The default value is 1000 if not set.
                      returned: when set
                      type: int
                    leafNodesToSearchPercent:
                      description:
                        - The default percentage of leaf nodes that any query may be searched.
                        - Must be in range 1-100, inclusive.
                        - The default value is 10 (means 10%) if not set.
                      returned: when set
                      type: int
                  description:
                    - Configuration options for using the tree-AH algorithm (Shallow tree + Asymmetric Hashing).
                    - 'Please refer to this paper for more details: https://arxiv.org/abs/1908.10396.'
                  returned: when set
                  type: dict
              description:
                - The configuration with regard to the algorithms used for efficient search.
                - This field may be required based on your configuration.
              returned: when set
              type: dict
            approximateNeighborsCount:
              description:
                - The default number of neighbors to find via approximate search before exact reordering is performed.
                - Exact reordering is a procedure where results returned by an approximate search algorithm are reordered via a more expensive distance computation.
                - Required if tree-AH algorithm is used.
              returned: when set
              type: int
            dimensions:
              description:
                - The number of dimensions of the input vectors.
              returned: always
              type: int
            distanceMeasureType:
              description:
                - The distance measure used in nearest neighbor search.
                - 'The value must be one of the followings: * SQUARED_L2_DISTANCE: Euclidean (L_2) Distance * L1_DISTANCE: Manhattan (L_1) Distance * COSINE_DISTANCE: Cosine Distance.'
                - Defined as 1 - cosine similarity.
                - '* DOT_PRODUCT_DISTANCE: Dot Product Distance.'
                - Defined as a negative of the dot product.
              returned: when set
              type: str
            featureNormType:
              description:
                - Type of normalization to be carried out on each vector.
                - 'The value must be one of the followings: * UNIT_L2_NORM: Unit L2 normalization type * NONE: No normalization type is specified.'
              returned: when set
              type: str
            shardSize:
              description:
                - Index data is split into equal parts to be processed.
                - These are called "shards".
                - The shard size must be specified when creating an index.
                - 'The value must be one of the followings: * SHARD_SIZE_SMALL: Small (2GB) * SHARD_SIZE_MEDIUM: Medium (20GB) * SHARD_SIZE_LARGE: Large (50GB).'
              returned: when set
              type: str
          description:
            - The configuration of the Matching Engine Index.
          returned: always
          type: dict
        contentsDeltaUri:
          description:
            - Allows inserting, updating  or deleting the contents of the Matching Engine Index.
            - The string must be a valid Cloud Storage directory path.
            - If this field is set when calling IndexService.UpdateIndex, then no other Index field can be also updated as part of the same call.
            - The expected structure and format of the files this URI points to is described at https://cloud.google.com/vertex-ai/docs/matching-engine/using-matching-engine#input-data-format.
          returned: when set
          type: str
        isCompleteOverwrite:
          description:
            - If this field is set together with contentsDeltaUri when calling IndexService.UpdateIndex, then existing content of the Index will be replaced by the data from the contentsDeltaUri.
          returned: when set
          type: bool
      description:
        - Additional information about the Index.
        - Although this field is not marked as required in the API specification, it is currently required when creating an Index and must be provided.
        - Attempts to create an Index without this field will result in an API error.
      returned: always
      type: dict
    metadataSchemaUri:
      description:
        - Points to a YAML file stored on Google Cloud Storage describing additional information about the Index, that is specific to it.
        - Unset if the Index does not have any additional information.
      returned: success
      type: str
    name:
      description:
        - The resource name of the Index.
      returned: success
      type: str
    updateTime:
      description:
        - The timestamp of when the Index was last updated in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
      returned: success
      type: str
  description: List of VertexAI.Index resources matching the supplied filters. May be empty, contain a single resource, or multiple resources.
  elements: dict
  returned: always
  type: list
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            filters=dict(
                type="list",
                elements="str",
            ),
            region=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    # info modules only require the "collection" url
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{region}-aiplatform.googleapis.com/v1/",
        base_uri="projects/{project}/locations/{region}/indexes",
        configs={},
    )

    info = gcp_v2.Resource(
        module.params,  # only need it to build the link
        module=module,
        product="VertexAI",
        kind="vertexai#index",
        op_configs=op_configs,
    )

    filter_exprs = module.params.get("filters") or []

    link = info.build_link("list")
    resources = info.list(link, key="indexes", filters=filter_exprs)

    module.exit_json(changed=False, resources=resources)


if __name__ == "__main__":
    main()
