#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - Models are deployed into it, and afterwards Endpoint is called to obtain predictions and explanations.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_vertexai_endpoint_info
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.endpoints)'
  - 'Official Documentation Guide: U(https://cloud.google.com/vertex-ai/docs)'
options:
  filters:
    description:
      - A list of filter expression strings used to filter the resources returned by the API.
      - Each string is a filter expression (e.g. C(some_field = "SOME_VALUE")).
      - Multiple expressions are combined with a logical AND.
      - Refer to the filter topic documentation U(https://cloud.google.com/sdk/gcloud/reference/topic/filters).
      - Refer to the IAP-160 filter syntax documentation U(https://google.aip.dev/160).
    elements: str
    type: list
  location:
    description:
      - The location for the resource.
    required: true
    type: str
  region:
    description:
      - The region for the resource.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: List GCP vertexai.Endpoint resources
"""  # noqa: E501

EXAMPLES = r"""
- name: List all gcp_vertexai_endpoint_info resources
  google.cloud.gcp_vertexai_endpoint_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result

- name: List gcp_vertexai_endpoint_info resources matching given filters
  google.cloud.gcp_vertexai_endpoint_info:
    filters:
      - display_name = "my-resource"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether any changes were made (always false for info modules).
  returned: always
  type: bool
resources:
  contains:
    createTime:
      description:
        - Output only.
        - Timestamp when this Endpoint was created.
      returned: success
      type: str
    dedicatedEndpointDns:
      description:
        - Output only.
        - DNS of the dedicated endpoint.
        - Will only be populated if dedicatedEndpointEnabled is true.
        - 'Format: `https://{endpointId}.{region}-{projectNumber}.prediction.vertexai.goog`.'
      returned: success
      type: str
    dedicatedEndpointEnabled:
      description:
        - If true, the endpoint will be exposed through a dedicated DNS [Endpoint.dedicated_endpoint_dns].
        - Your request to the dedicated DNS will be isolated from other users' traffic and will have better performance and reliability.
        - 'Note: Once you enabled dedicated endpoint, you won''t be able to send request to the shared DNS {region}-aiplatform.googleapis.com.'
        - The limitation will be removed soon.
      returned: when set
      type: bool
    deployedModels:
      contains:
        automaticResources:
          contains:
            maxReplicaCount:
              description:
                - The maximum number of replicas this DeployedModel may be deployed on when the traffic against it increases.
                - If the requested value is too large, the deployment will error, but if deployment succeeds then the ability to scale the model to that many replicas is guaranteed (barring service outages).
                - If traffic against the DeployedModel increases beyond what its replicas at maximum may handle, a portion of the traffic will be dropped.
                - If this value is not provided, a no upper bound for scaling under heavy traffic will be assume, though Vertex AI may be unable to scale beyond certain replica number.
              returned: success
              type: int
            minReplicaCount:
              description:
                - The minimum number of replicas this DeployedModel will be always deployed on.
                - If traffic against it increases, it may dynamically be deployed onto more replicas up to max_replica_count, and as traffic decreases, some of these extra replicas may be freed.
                - If the requested value is too large, the deployment will error.
              returned: success
              type: int
          description:
            - A description of resources that to large degree are decided by Vertex AI, and require only a modest additional configuration.
          returned: success
          type: dict
        createTime:
          description:
            - Output only.
            - Timestamp when the DeployedModel was created.
          returned: success
          type: str
        dedicatedResources:
          contains:
            autoscalingMetricSpecs:
              contains:
                metricName:
                  description:
                    - The resource metric name.
                    - 'Supported metrics: * For Online Prediction: * `aiplatform.googleapis.com/prediction/online/accelerator/duty_cycle` * `aiplatform.googleapis.com/prediction/online/cpu/utilization`.'
                  returned: success
                  type: str
                target:
                  description:
                    - The target resource utilization in percentage (1% - 100%) for the given metric; once the real usage deviates from the target by a certain percentage, the machine replicas change.
                    - The default value is 60 (representing 60%) if not provided.
                  returned: success
                  type: int
              description:
                - The metric specifications that overrides a resource utilization metric (CPU utilization, accelerator's duty cycle, and so on) target value (default to 60 if not set).
                - At most one entry is allowed per metric.
                - If machine_spec.accelerator_count is above 0, the autoscaling will be based on both CPU utilization and accelerator's duty cycle metrics and scale up when either metrics exceeds its target value while scale down if both metrics are under their target value.
                - The default target value is 60 for both metrics.
                - If machine_spec.accelerator_count is 0, the autoscaling will be based on CPU utilization metric only with default target value 60 if not explicitly set.
                - For example, in the case of Online Prediction, if you want to override target CPU utilization to 80, you should set autoscaling_metric_specs.metric_name to `aiplatform.googleapis.com/prediction/online/cpu/utilization` and autoscaling_metric_specs.target to `80`.
              elements: dict
              returned: success
              type: list
            machineSpec:
              contains:
                acceleratorCount:
                  description:
                    - The number of accelerators to attach to the machine.
                  returned: success
                  type: int
                acceleratorType:
                  description:
                    - The type of accelerator(s) that may be attached to the machine as per accelerator_count.
                    - See possible values [here](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/MachineSpec#AcceleratorType).
                  returned: success
                  type: str
                machineType:
                  description:
                    - The type of the machine.
                    - See the [list of machine types supported for prediction](https://cloud.google.com/vertex-ai/docs/predictions/configure-compute#machine-types) See the [list of machine types supported for custom training](https://cloud.google.com/vertex-ai/docs/training/configure-compute#machine-types).
                    - For DeployedModel this field is optional, and the default value is `n1-standard-2`.
                    - For BatchPredictionJob or as part of WorkerPoolSpec this field is required.
                    - 'TODO: Try to better unify the required vs optional.'
                  returned: success
                  type: str
              description:
                - The specification of a single machine used by the prediction.
              returned: success
              type: dict
            maxReplicaCount:
              description:
                - The maximum number of replicas this DeployedModel may be deployed on when the traffic against it increases.
                - If the requested value is too large, the deployment will error, but if deployment succeeds then the ability to scale the model to that many replicas is guaranteed (barring service outages).
                - If traffic against the DeployedModel increases beyond what its replicas at maximum may handle, a portion of the traffic will be dropped.
                - If this value is not provided, will use min_replica_count as the default value.
                - The value of this field impacts the charge against Vertex CPU and GPU quotas.
                - Specifically, you will be charged for max_replica_count * number of cores in the selected machine type) and (max_replica_count * number of GPUs per replica in the selected machine type).
              returned: success
              type: int
            minReplicaCount:
              description:
                - The minimum number of machine replicas this DeployedModel will be always deployed on.
                - This value must be greater than or equal to 1.
                - If traffic against the DeployedModel increases, it may dynamically be deployed onto more replicas, and as traffic decreases, some of these extra replicas may be freed.
              returned: success
              type: int
          description:
            - A description of resources that are dedicated to the DeployedModel, and that need a higher degree of manual configuration.
          returned: success
          type: dict
        displayName:
          description:
            - The display name of the DeployedModel.
            - If not provided upon creation, the Model's display_name is used.
          returned: success
          type: str
        enableAccessLogging:
          description:
            - These logs are like standard server access logs, containing information like timestamp and latency for each prediction request.
            - Note that Stackdriver logs may incur a cost, especially if your project receives prediction requests at a high queries per second rate (QPS).
            - Estimate your costs before enabling this option.
          returned: success
          type: bool
        enableContainerLogging:
          description:
            - If true, the container of the DeployedModel instances will send `stderr` and `stdout` streams to Stackdriver Logging.
            - Only supported for custom-trained Models and AutoML Tabular Models.
          returned: success
          type: bool
        id:
          description:
            - The ID of the DeployedModel.
            - If not provided upon deployment, Vertex AI will generate a value for this ID.
            - This value should be 1-10 characters, and valid characters are /[0-9]/.
          returned: success
          type: str
        model:
          description:
            - The name of the Model that this is the deployment of.
            - Note that the Model may be in a different location than the DeployedModel's Endpoint.
          returned: success
          type: str
        modelVersionId:
          description:
            - Output only.
            - The version ID of the model that is deployed.
          returned: success
          type: str
        privateEndpoints:
          contains:
            explainHttpUri:
              description:
                - Output only.
                - Http(s) path to send explain requests.
              returned: success
              type: str
            healthHttpUri:
              description:
                - Output only.
                - Http(s) path to send health check requests.
              returned: success
              type: str
            predictHttpUri:
              description:
                - Output only.
                - Http(s) path to send prediction requests.
              returned: success
              type: str
            serviceAttachment:
              description:
                - Output only.
                - The name of the service attachment resource.
                - Populated if private service connect is enabled.
              returned: success
              type: str
          description:
            - Output only.
            - Provide paths for users to send predict/explain/health requests directly to the deployed model services running on Cloud via private services access.
            - This field is populated if network is configured.
          returned: success
          type: dict
        serviceAccount:
          description:
            - The service account that the DeployedModel's container runs as.
            - Specify the email address of the service account.
            - If this service account is not specified, the container runs as a service account that doesn't have access to the resource project.
            - Users deploying the Model must have the `iam.serviceAccounts.actAs` permission on this service account.
          returned: success
          type: str
        sharedResources:
          description:
            - The resource name of the shared DeploymentResourcePool to deploy on.
            - 'Format: projects/{project}/locations/{location}/deploymentResourcePools/{deployment_resource_pool}.'
          returned: success
          type: str
      description:
        - Output only.
        - The models deployed in this Endpoint.
        - To add or remove DeployedModels use EndpointService.DeployModel and EndpointService.UndeployModel respectively.
        - Models can also be deployed and undeployed using the [Cloud Console](https://console.cloud.google.com/vertex-ai/).
      elements: dict
      returned: success
      type: list
    description:
      description:
        - The description of the Endpoint.
      returned: when set
      type: str
    displayName:
      description:
        - The display name of the Endpoint.
        - The name can be up to 128 characters long and can consist of any UTF-8 characters.
      returned: always
      type: str
    encryptionSpec:
      contains:
        kmsKeyName:
          description:
            - The Cloud KMS resource identifier of the customer managed encryption key used to protect a resource.
            - 'Has the form: `projects/my-project/locations/my-region/keyRings/my-kr/cryptoKeys/my-key`.'
            - The key needs to be in the same region as where the compute resource is created.
          returned: always
          type: str
      description:
        - Customer-managed encryption key spec for an Endpoint.
        - If set, this Endpoint and all sub-resources of this Endpoint will be secured by this key.
      returned: when set
      type: dict
    labels:
      description:
        - The labels with user-defined metadata to organize your Endpoints.
        - Label keys and values can be no longer than 64 characters (Unicode codepoints), can only contain lowercase letters, numeric characters, underscores and dashes.
        - International characters are allowed.
        - See https://goo.gl/xmQnxf for more information and examples of labels.
        - '**Note**: This field is non-authoritative, and will only manage the labels present in your configuration.'
      returned: when set
      type: dict
    modelDeploymentMonitoringJob:
      description:
        - Output only.
        - Resource name of the Model Monitoring job associated with this Endpoint if monitoring is enabled by CreateModelDeploymentMonitoringJob.
        - 'Format: `projects/{project}/locations/{location}/modelDeploymentMonitoringJobs/{model_deployment_monitoring_job}`.'
      returned: success
      type: str
    network:
      description:
        - The full name of the Google Compute Engine [network](https://cloud.google.com//compute/docs/networks-and-firewalls#networks) to which the Endpoint should be peered.
        - Private services access must already be configured for the network.
        - If left unspecified, the Endpoint is not peered with any network.
        - Only one of the fields, network or enable_private_service_connect, can be set.
        - '[Format](https://cloud.google.com/compute/docs/reference/rest/v1/networks/insert): `projects/{project}/global/networks/{network}`.'
        - Where `{project}` is a project number, as in `12345`, and `{network}` is network name.
        - Only one of the fields, `network` or `privateServiceConnectConfig`, can be set.
      returned: when set
      type: str
    predictRequestResponseLoggingConfig:
      contains:
        bigqueryDestination:
          contains:
            outputUri:
              description:
                - BigQuery URI to a project or table, up to 2000 characters long.
                - When only the project is specified, the Dataset and Table is created.
                - When the full table reference is specified, the Dataset must exist and table must not exist.
                - 'Accepted forms: - BigQuery path.'
                - 'For example: `bq://projectId` or `bq://projectId.bqDatasetId` or `bq://projectId.bqDatasetId.bqTableId`.'
              returned: when set
              type: str
          description:
            - BigQuery table for logging.
            - If only given a project, a new dataset will be created with name `logging_<endpoint-display-name>_<endpoint-id>` where will be made BigQuery-dataset-name compatible (e.g.
            - most special characters will become underscores).
            - If no table name is given, a new table will be created with name `request_response_logging`.
          returned: when set
          type: dict
        enabled:
          description:
            - If logging is enabled or not.
          returned: when set
          type: bool
      description:
        - Configures the request-response logging for online prediction.
      returned: when set
      type: dict
    privateServiceConnectConfig:
      contains:
        enablePrivateServiceConnect:
          description:
            - If true, expose the IndexEndpoint via private service connect.
          returned: always
          type: bool
        enableSecurePrivateServiceConnect:
          description:
            - If set to true, enable secure private service connect with IAM authorization.
            - Otherwise, private service connect will be done without authorization.
            - Note latency will be slightly increased if authorization is enabled.
          returned: when set
          type: bool
        projectAllowlist:
          description:
            - A list of Projects from which the forwarding rule will target the service attachment.
          elements: str
          returned: when set
          type: list
        pscAutomationConfigs:
          contains:
            errorMessage:
              description:
                - Error message if the PSC service automation failed.
              returned: success
              type: str
            forwardingRule:
              description:
                - Forwarding rule created by the PSC service automation.
              returned: success
              type: str
            ipAddress:
              description:
                - IP address rule created by the PSC service automation.
              returned: success
              type: str
            network:
              description:
                - The full name of the Google Compute Engine [network](https://cloud.google.com/compute/docs/networks-and-firewalls#networks).
                - '[Format](https://cloud.google.com/compute/docs/reference/rest/v1/networks/get): projects/{project}/global/networks/{network}.'
              returned: always
              type: str
            projectId:
              description:
                - Project id used to create forwarding rule.
              returned: always
              type: str
            state:
              description:
                - The state of the PSC service automation.
              returned: success
              type: str
          description:
            - List of projects and networks where the PSC endpoints will be created.
            - This field is used by Online Inference(Prediction) only.
          elements: dict
          returned: when set
          type: list
      description:
        - Configuration for private service connect.
        - '`network` and `privateServiceConnectConfig` are mutually exclusive.'
      returned: when set
      type: dict
    trafficSplit:
      description:
        - A map from a DeployedModel's id to the percentage of this Endpoint's traffic that should be forwarded to that DeployedModel.
        - If a DeployedModel's id is not listed in this map, then it receives no traffic.
        - The traffic percentage values must add up to 100, or map must be empty if the Endpoint is to not accept any traffic at a moment.
        - See the `deployModel` [example](https://cloud.google.com/vertex-ai/docs/general/deployment#deploy_a_model_to_an_endpoint) and [documentation](https://cloud.google.com/vertex-ai/docs/reference/rest/v1beta1/projects.locations.endpoints/deployModel) for more information.
        - ~> **Note:** To set the map to empty, set `"{}"`, apply, and then remove the field from your config.
      returned: when set
      type: str
    updateTime:
      description:
        - Output only.
        - Timestamp when this Endpoint was last updated.
      returned: success
      type: str
  description: List of VertexAI.Endpoint resources matching the supplied filters. May be empty, contain a single resource, or multiple resources.
  elements: dict
  returned: always
  type: list
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            filters=dict(
                type="list",
                elements="str",
            ),
            location=dict(
                type="str",
                required=True,
            ),
            region=dict(
                type="str",
            ),
        ),
        supports_check_mode=True,
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    # info modules only require the "collection" url
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{region}-aiplatform.googleapis.com/v1/",
        base_uri="projects/{project}/locations/{location}/endpoints",
        configs={},
    )

    info = gcp_v2.Resource(
        module.params,  # only need it to build the link
        module=module,
        product="VertexAI",
        kind="vertexai#endpoint",
        op_configs=op_configs,
    )

    filter_exprs = module.params.get("filters") or []

    link = info.build_link("list")
    resources = info.list(link, key="endpoints", filters=filter_exprs)

    module.exit_json(changed=False, resources=resources)


if __name__ == "__main__":
    main()
