#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - '''Colab Enterprise Notebook Execution Schedules.'''
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_colab_schedule
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.schedules)'
  - 'Schedule a notebook run Guide: U(https://cloud.google.com/colab/docs/schedule-notebook-run)'
options:
  allow_queueing:
    description:
      - Whether new scheduled runs can be queued when max_concurrent_runs limit is reached.
      - If set to true, new runs will be queued instead of skipped.
      - Default to false.
    type: bool
  create_notebook_execution_job_request:
    description:
      - Request for google_colab_notebook_execution.
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    suboptions:
      notebook_execution_job:
        description:
          - The NotebookExecutionJob to create.
        required: true
        suboptions:
          dataform_repository_source:
            description:
              - The Dataform Repository containing the input notebook.
            suboptions:
              commit_sha:
                description:
                  - The commit SHA to read repository with.
                  - If unset, the file will be read at HEAD.
                type: str
              dataform_repository_resource_name:
                description:
                  - The resource name of the Dataform Repository.
                required: true
                type: str
            type: dict
          display_name:
            description:
              - The display name of the Notebook Execution.
            required: true
            type: str
          execution_timeout:
            description:
              - Max running time of the execution job in seconds (default 86400s / 24 hrs).
              - A duration in seconds with up to nine fractional digits, ending with "s".
              - 'Example: "3.5s".'
            type: str
          execution_user:
            description:
              - The user email to run the execution as.
            type: str
          gcs_notebook_source:
            description:
              - The Cloud Storage uri for the input notebook.
            suboptions:
              generation:
                description:
                  - The version of the Cloud Storage object to read.
                  - If unset, the current version of the object is read.
                  - See https://cloud.google.com/storage/docs/metadata#generation-number.
                type: str
              uri:
                description:
                  - The Cloud Storage uri pointing to the ipynb file.
                  - 'Format: gs://bucket/notebook_file.ipynb.'
                required: true
                type: str
            type: dict
          gcs_output_uri:
            description:
              - The Cloud Storage location to upload the result to.
              - Format:`gs://bucket-name`.
            required: true
            type: str
          notebook_runtime_template_resource_name:
            description:
              - The NotebookRuntimeTemplate to source compute configuration from.
            required: true
            type: str
          service_account:
            description:
              - The service account to run the execution as.
            type: str
        type: dict
    type: dict
  cron:
    description:
      - Cron schedule (https://en.wikipedia.org/wiki/Cron) to launch scheduled runs.
    required: true
    type: str
  desired_state:
    choices:
      - ACTIVE
      - PAUSED
    default: ACTIVE
    description:
      - Desired state of the Colab Schedule.
      - Set this field to `ACTIVE` to start/resume the schedule, and `PAUSED` to pause the schedule.
    type: str
  display_name:
    description:
      - The display name of the Schedule.
    required: true
    type: str
  end_time:
    description:
      - Timestamp after which no new runs can be scheduled.
      - If specified, the schedule will be completed when either end_time is reached or when scheduled_run_count >= max_run_count.
      - Must be in the RFC 3339 (https://www.ietf.org/rfc/rfc3339.txt) format.
    type: str
  location:
    description:
      - 'The location for the resource: https://cloud.google.com/colab/docs/locations.'
    required: true
    type: str
  max_concurrent_run_count:
    description:
      - Maximum number of runs that can be started concurrently for this Schedule.
      - This is the limit for starting the scheduled requests and not the execution of the notebook execution jobs created by the requests.
    required: true
    type: str
  max_run_count:
    description:
      - Maximum run count of the schedule.
      - If specified, The schedule will be completed when either startedRunCount >= maxRunCount or when endTime is reached.
      - If not specified, new runs will keep getting scheduled until this Schedule is paused or deleted.
      - Already scheduled runs will be allowed to complete.
      - Unset if not specified.
    type: str
  start_time:
    description:
      - The timestamp after which the first run can be scheduled.
      - Defaults to the schedule creation time.
      - Must be in the RFC 3339 (https://www.ietf.org/rfc/rfc3339.txt) format.
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist in GCP.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Creates a GCP Colab.Schedule resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create Basic Schedule
  google.cloud.gcp_colab_schedule:
    display_name: my-schedule
    state: present
    location: us-central1
    max_concurrent_run_count: 2
    cron: "TZ=America/Los_Angeles * * * * *"
    create_notebook_execution_job_request:
      notebook_execution_job:
        display_name: my-notebook-execution
        gcs_notebook_source:
          uri: gs://my-bucket/input/my-notebook.json
        notebook_runtime_template_resource_name: projects/my-project/locations/us-central1/notebookRuntimeTemplates/my-runtime-template
        gcs_output_uri: gs://my-bucket/output/
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"

################################################################################

- name: Create Paused Schedule
  google.cloud.gcp_colab_schedule:
    display_name: my-schedule
    state: present
    location: us-central1
    desired_state: PAUSED
    max_concurrent_run_count: 2
    cron: "TZ=America/Los_Angeles * * * * *"
    create_notebook_execution_job_request:
      notebook_execution_job:
        display_name: my-notebook-execution
        gcs_notebook_source:
          uri: gs://my-bucket/input/my-notebook.json
        notebook_runtime_template_resource_name: projects/my-project/locations/us-central1/notebookRuntimeTemplates/my-runtime-template
        gcs_output_uri: gs://my-bucket/output/
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
name:
  description:
    - The resource name of the Schedule.
  returned: success
  type: str
state:
  description:
    - Output only.
    - The state of the schedule.
  returned: success
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_utils as gcp
import types

# BEGIN Custom imports
import copy

# END Custom imports


def build_link(module_params, uri):
    params = module_params.copy()

    return ("https://{location}-aiplatform.googleapis.com/v1/" + uri).format(**params)


class CreateNotebookExecutionJobRequest(gcp.Resource):
    def _request(self):
        return {
            "notebookExecutionJob": gcp.remove_empties(
                CreateNotebookExecutionJobRequestNotebookExecutionJob(
                    self.request.get("notebook_execution_job", {})
                ).to_request()
            ),  # remove empty values
        }

    def _response(self):
        return {
            "notebookExecutionJob": CreateNotebookExecutionJobRequestNotebookExecutionJob().from_response(
                self.response.get("notebookExecutionJob", {})
            ),
        }


class CreateNotebookExecutionJobRequestNotebookExecutionJob(gcp.Resource):
    def _request(self):
        return {
            "dataformRepositorySource": gcp.remove_empties(
                CreateNotebookExecutionJobRequestNotebookExecutionJobDataformRepositorySource(
                    self.request.get("dataform_repository_source", {})
                ).to_request()
            ),  # remove empty values
            "displayName": self.request.get("display_name"),
            "executionTimeout": self.request.get("execution_timeout"),
            "executionUser": self.request.get("execution_user"),
            "gcsNotebookSource": gcp.remove_empties(
                CreateNotebookExecutionJobRequestNotebookExecutionJobGcsNotebookSource(
                    self.request.get("gcs_notebook_source", {})
                ).to_request()
            ),  # remove empty values
            "gcsOutputUri": self.request.get("gcs_output_uri"),
            "notebookRuntimeTemplateResourceName": self.request.get("notebook_runtime_template_resource_name"),
            "serviceAccount": self.request.get("service_account"),
        }

    def _response(self):
        return {
            "dataformRepositorySource": CreateNotebookExecutionJobRequestNotebookExecutionJobDataformRepositorySource().from_response(
                self.response.get("dataformRepositorySource", {})
            ),
            "displayName": self.response.get("displayName"),
            "executionTimeout": self.response.get("executionTimeout"),
            "executionUser": self.response.get("executionUser"),
            "gcsNotebookSource": CreateNotebookExecutionJobRequestNotebookExecutionJobGcsNotebookSource().from_response(
                self.response.get("gcsNotebookSource", {})
            ),
            "gcsOutputUri": self.response.get("gcsOutputUri"),
            "notebookRuntimeTemplateResourceName": self.response.get("notebookRuntimeTemplateResourceName"),
            "serviceAccount": self.response.get("serviceAccount"),
        }


class CreateNotebookExecutionJobRequestNotebookExecutionJobDataformRepositorySource(gcp.Resource):
    def _request(self):
        return {
            "commitSha": self.request.get("commit_sha"),
            "dataformRepositoryResourceName": self.request.get("dataform_repository_resource_name"),
        }

    def _response(self):
        return {
            "commitSha": self.response.get("commitSha"),
            "dataformRepositoryResourceName": self.response.get("dataformRepositoryResourceName"),
        }


class CreateNotebookExecutionJobRequestNotebookExecutionJobGcsNotebookSource(gcp.Resource):
    def _request(self):
        return {
            "generation": self.request.get("generation"),
            "uri": self.request.get("uri"),
        }

    def _response(self):
        return {
            "generation": self.response.get("generation"),
            "uri": self.response.get("uri"),
        }


class Colab(gcp.Resource):
    def _request(self):
        return {
            "allowQueueing": self.request.get("allow_queueing"),
            "createNotebookExecutionJobRequest": gcp.remove_empties(
                CreateNotebookExecutionJobRequest(
                    self.request.get("create_notebook_execution_job_request", {})
                ).to_request()
            ),  # remove empty values
            "cron": self.request.get("cron"),
            "displayName": self.request.get("display_name"),
            "endTime": self.request.get("end_time"),
            "maxConcurrentRunCount": self.request.get("max_concurrent_run_count"),
            "maxRunCount": self.request.get("max_run_count"),
            "startTime": self.request.get("start_time"),
        }

    def _response(self):
        return {
            "allowQueueing": self.response.get("allowQueueing"),
            "createNotebookExecutionJobRequest": CreateNotebookExecutionJobRequest().from_response(
                self.response.get("createNotebookExecutionJobRequest", {})
            ),
            "cron": self.response.get("cron"),
            "displayName": self.response.get("displayName"),
            "endTime": self.response.get("endTime"),
            "maxConcurrentRunCount": self.response.get("maxConcurrentRunCount"),
            "maxRunCount": self.response.get("maxRunCount"),
            "name": self.response.get("name"),
            "startTime": self.response.get("startTime"),
        }


################################################################################
# Main
################################################################################


def encode(self, obj):
    """
    This is a function bound to the main resource object. Its input is the object returned from to_request()
    and it mutates it before it is sent to the API.
    """
    # --------- BEGIN custom encoder code ---------
    # I am using "change" state to cheat and indicate the desired state is being changed
    if self._state in ["absent", "change"]:
        return {}
    # createNotebookExecutionJobRequest does not exist in update requests
    r = copy.deepcopy(obj)
    if self._state == "update":
        r.pop("createNotebookExecutionJobRequest")
    else:
        # for create requests, we need to set the parent, idk why it is done this way
        r["createNotebookExecutionJobRequest"]["parent"] = (
            "projects/" + self.module.params.get("project") + "/locations/" + self.module.params.get("location")
        )

    return r

    # --------- END custom encoder code ---------


def decode(self, obj):
    """
    This is a function bound to the main resource object. Its input is the object returned from from_response()
    and it mutates it before it is returned to the module caller.
    """
    # --------- BEGIN custom decoder code ---------
    # flatten the schedules list to a single object
    r = copy.deepcopy(obj)
    if not gcp.empty(obj):
        schedules = r.pop("schedules", [])
        for schedule in schedules:
            if schedule.get("displayName") == self.module.params.get("display_name"):
                r.update(schedule)
                break
    return r

    # --------- END custom decoder code ---------


def main():
    """Main function"""

    module = gcp.Module(
        argument_spec=dict(
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            allow_queueing=dict(
                type="bool",
            ),
            create_notebook_execution_job_request=dict(
                type="dict",
                required=True,
                options=dict(
                    notebook_execution_job=dict(
                        type="dict",
                        required=True,
                        options=dict(
                            dataform_repository_source=dict(
                                type="dict",
                                options=dict(
                                    commit_sha=dict(
                                        type="str",
                                    ),
                                    dataform_repository_resource_name=dict(
                                        type="str",
                                        required=True,
                                    ),
                                ),
                            ),
                            display_name=dict(
                                type="str",
                                required=True,
                            ),
                            execution_timeout=dict(
                                type="str",
                            ),
                            execution_user=dict(
                                type="str",
                            ),
                            gcs_notebook_source=dict(
                                type="dict",
                                options=dict(
                                    generation=dict(
                                        type="str",
                                    ),
                                    uri=dict(
                                        type="str",
                                        required=True,
                                    ),
                                ),
                            ),
                            gcs_output_uri=dict(
                                type="str",
                                required=True,
                            ),
                            notebook_runtime_template_resource_name=dict(
                                type="str",
                                required=True,
                            ),
                            service_account=dict(
                                type="str",
                            ),
                        ),
                        mutually_exclusive=[
                            ["dataform_repository_source", "gcs_notebook_source"],
                            ["execution_user", "service_account"],
                        ],
                        required_one_of=[
                            ["dataform_repository_source", "gcs_notebook_source"],
                            ["execution_user", "service_account"],
                        ],
                    )
                ),
            ),
            cron=dict(
                type="str",
                required=True,
            ),
            desired_state=dict(
                type="str",
                default="ACTIVE",
                choices=["ACTIVE", "PAUSED"],
            ),
            display_name=dict(
                type="str",
                required=True,
            ),
            end_time=dict(
                type="str",
            ),
            location=dict(
                type="str",
                required=True,
            ),
            max_concurrent_run_count=dict(
                type="str",
                required=True,
            ),
            max_run_count=dict(
                type="str",
            ),
            start_time=dict(
                type="str",
            ),
        )
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp.ResourceOpConfigs(
        {
            "base_url": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/schedules",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "create": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/schedules",
                    "async_uri": "",
                    "verb": "POST",
                    "timeout_minutes": 20,
                }
            ),
            "delete": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/schedules/{name}",
                    "async_uri": "{op_id}",
                    "verb": "DELETE",
                    "timeout_minutes": 20,
                }
            ),
            "read": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/schedules/{name}",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "update": gcp.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{location}/schedules/{name}",
                    "async_uri": "",
                    "verb": "PATCH",
                    "timeout_minutes": 20,
                }
            ),
        }
    )

    params = gcp.remove_nones(module.params)
    resource = Colab(params, module=module, product="Colab", kind="colab#schedule")
    read_uri = op_configs.read.uri

    resource._state = state  # store the state in the resource object
    # Bind the encode and decode functions to the resource object
    resource.encode_func = types.MethodType(encode, resource)
    resource.decode_func = types.MethodType(decode, resource)

    custom_diff = None  # Set this variable if you want to implement custom diff logic

    # --------- BEGIN pre-read custom code ---------
    def change_state(state_link, resource, verb):
        """Change the state of the runtime"""

        resource._state = "change"
        state_func = getattr(resource, "post")
        return state_func(state_link + f":{verb}")

    # for this module, we're hitting the list endpoint and filtering on display name
    read_uri = op_configs.base_url.uri + "?filter=displayName=" + params.get("display_name")

    # --------- END pre-read custom code ---------

    read_url = build_link(params, read_uri)
    existing_obj = resource.decode_func(resource.get(read_url, allow_not_found=True) or {})
    new_obj = {}
    gcp.debug(module, existing=existing_obj, post=False)

    # --------- BEGIN post-read custom code ---------
    if not gcp.empty(existing_obj):
        if existing_obj.get("state") != params.get("desired_state"):
            custom_diff = True  # force update code path

    # --------- END post-read custom code ---------

    if custom_diff is not None:
        is_different = custom_diff
    else:
        is_different = resource.diff(gcp.remove_empties(existing_obj))
    gcp.debug(
        module,
        request=gcp.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp.empty(existing_obj):
        if state == "present":
            create_uri = op_configs.create.uri
            create_async_uri = op_configs.create.async_uri
            try:
                # --------- BEGIN create code ---------
                is_async = create_async_uri != ""
                create_link = build_link(params, create_uri)
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                async_create_func = getattr(resource, op_configs.create.verb + "_async")
                async_create_link = build_link(params, "") + create_async_uri
                gcp.debug(
                    module,
                    msg="Creating resource",
                    create_link=create_link,
                    async_create_link=async_create_link,
                    is_async=is_async,
                )

                if is_async:
                    new_obj = async_create_func(create_link, async_link=async_create_link, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.decode_func(new_obj)
                gcp.debug(module, new=new_obj, action="create", post=False)
                # --------- BEGIN post-create custom code ---------
                # pause schedule if desired_state is PAUSED
                if params.get("desired_state") == "PAUSED":
                    params["name"] = new_obj["name"].split("/")[-1]
                    gcp.debug(module, msg="Changing schedule state to PAUSED")
                    state_link = build_link(params, op_configs.update.uri)
                    new_obj = change_state(state_link, resource, "pause")

                # --------- END post-create custom code ---------
                gcp.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            delete_uri = op_configs.delete.uri
            delete_async_uri = op_configs.delete.async_uri
            try:
                # --------- BEGIN delete code ---------
                # --------- BEGIN pre-delete custom code ---------
                params["name"] = existing_obj["name"].split("/")[-1]
                # --------- END pre-delete custom code ---------
                is_async = delete_async_uri != ""
                delete_link = build_link(params, delete_uri)
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                async_delete_func = getattr(resource, op_configs.delete.verb + "_async")
                async_delete_link = build_link(params, "") + delete_async_uri
                gcp.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_delete_link=async_delete_link,
                    is_async=is_async,
                )
                if is_async:
                    new_obj = async_delete_func(delete_link, async_link=async_delete_link, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.decode_func(new_obj)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                update_uri = op_configs.update.uri
                update_async_uri = op_configs.update.async_uri
                try:
                    # --------- BEGIN update code ---------
                    # --------- BEGIN pre-update custom code ---------
                    resource._state = "update"
                    params["name"] = existing_obj["name"].split("/")[-1]
                    update_mask = [
                        "cron",
                        "startTime",
                        "endTime",
                        "maxRunCount",
                        "maxConcurrentRunCount",
                        "maxConcurrentActiveRunCount",
                        "allowQueueing",
                    ]
                    update_uri += "?updateMask=" + ",".join(update_mask)

                    # --------- END pre-update custom code ---------
                    is_async = update_async_uri != ""
                    update_link = build_link(params, update_uri)
                    update_retries = op_configs.update.timeout
                    update_func = getattr(resource, op_configs.update.verb)
                    async_update_func = getattr(resource, op_configs.update.verb + "_async")
                    async_update_link = build_link(params, "") + update_async_uri
                    gcp.debug(
                        module,
                        msg="Updating resource",
                        update_link=update_link,
                        async_update_link=async_update_link,
                        is_async=is_async,
                    )
                    if is_async:
                        new_obj = async_update_func(update_link, async_link=async_update_link, retries=update_retries)
                    else:
                        new_obj = update_func(update_link)
                    new_obj = resource.decode_func(new_obj)
                    gcp.debug(module, new=new_obj, action="update", post=False)
                    # --------- BEGIN post-update custom code ---------
                    if params.get("desired_state") != existing_obj.get("state"):
                        gcp.debug(module, msg="Changing schedule state to {params.get('desired_state')}")
                        state_link = build_link(params, op_configs.update.uri)
                        new_obj = change_state(
                            state_link, resource, "pause" if params.get("desired_state") == "PAUSED" else "resume"
                        )
                        new_obj = resource.decode_func(new_obj)
                        changed = True

                    # --------- END post-update custom code ---------
                    gcp.debug(module, new=new_obj, action="update", post=True)
                    # --------- END update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj = resource.from_response(resource.get(read_url, allow_not_found=True) or {})
    new_obj.update({"changed": changed})
    gcp.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
