#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - An attestor that attests to container image artifacts.
extends_documentation_fragment:
  - google.cloud.gcp
  - google.cloud.info
module: gcp_binaryauthorization_attestor_info
notes:
  - 'API Reference: U(https://cloud.google.com/binary-authorization/docs/reference/rest/)'
  - 'Official Documentation Guide: U(https://cloud.google.com/binary-authorization/)'
options:
  filters:
    elements: str
    type: list
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: List BinaryAuthorization.Attestor resources
"""  # noqa: E501

EXAMPLES = r"""
- name: List all gcp_binaryauthorization_attestor_info resources
  google.cloud.gcp_binaryauthorization_attestor_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result

- name: List gcp_binaryauthorization_attestor_info resources matching given filters
  google.cloud.gcp_binaryauthorization_attestor_info:
    filters:
      - display_name = "my-resource"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether any changes were made (always false for info modules).
  returned: always
  type: bool
resources:
  contains:
    description:
      description:
        - A descriptive comment.
        - This field may be updated.
        - The field may be displayed in chooser dialogs.
      returned: when set
      type: str
    name:
      description:
        - The resource name.
      returned: always
      type: str
    userOwnedGrafeasNote:
      contains:
        delegationServiceAccountEmail:
          description:
            - This field will contain the service account email address that this Attestor will use as the principal when querying Container Analysis.
            - Attestor administrators must grant this service account the IAM role needed to read attestations from the noteReference in Container Analysis (containeranalysis.notes.occurrences.viewer).
            - This email address is fixed for the lifetime of the Attestor, but callers should not make any other assumptions about the service account email; future versions may use an email based on a different naming pattern.
          returned: success
          type: str
        noteReference:
          description:
            - The resource name of a ATTESTATION_AUTHORITY Note, created by the user.
            - If the Note is in a different project from the Attestor, it should be specified in the format `projects/*/notes/*` (or the legacy `providers/*/notes/*`).
            - This field may not be updated.
            - An attestation by this attestor is stored as a Container Analysis ATTESTATION_AUTHORITY Occurrence that names a container image and that links to this Note.
          returned: always
          type: str
        publicKeys:
          contains:
            asciiArmoredPgpPublicKey:
              description:
                - ASCII-armored representation of a PGP public key, as the entire output by the command `gpg --export --armor foo@example.com` (either LF or CRLF line endings).
                - When using this field, id should be left blank.
                - The BinAuthz API handlers will calculate the ID and fill it in automatically.
                - BinAuthz computes this ID as the OpenPGP RFC4880 V4 fingerprint, represented as upper-case hex.
                - If id is provided by the caller, it will be overwritten by the API-calculated ID.
              returned: when set
              type: str
            comment:
              description:
                - A descriptive comment.
                - This field may be updated.
              returned: when set
              type: str
            id:
              description:
                - The ID of this public key.
                - Signatures verified by BinAuthz must include the ID of the public key that can be used to verify them, and that ID must match the contents of this field exactly.
                - Additional restrictions on this field can be imposed based on which public key type is encapsulated.
                - See the documentation on publicKey cases below for details.
              returned: when set
              type: str
            pkixPublicKey:
              contains:
                publicKeyPem:
                  description:
                    - A PEM-encoded public key, as described in `https://tools.ietf.org/html/rfc7468#section-13`.
                  returned: when set
                  type: str
                signatureAlgorithm:
                  description:
                    - The signature algorithm used to verify a message against a signature using this key.
                    - These signature algorithm must match the structure and any object identifiers encoded in publicKeyPem (i.e.
                    - this algorithm must match that of the public key).
                  returned: when set
                  type: str
              description:
                - A raw PKIX SubjectPublicKeyInfo format public key.
                - 'NOTE: id may be explicitly provided by the caller when using this type of public key, but it MUST be a valid RFC3986 URI.'
                - If id is left blank, a default one will be computed based on the digest of the DER encoding of the public key.
              returned: when set
              type: dict
          description:
            - Public keys that verify attestations signed by this attestor.
            - This field may be updated.
            - If this field is non-empty, one of the specified public keys must verify that an attestation was signed by this attestor for the image specified in the admission request.
            - If this field is empty, this attestor always returns that no valid attestations exist.
          elements: dict
          returned: when set
          type: list
      description:
        - A Container Analysis ATTESTATION_AUTHORITY Note, created by the user.
      returned: always
      type: dict
  description: List of BinaryAuthorization.Attestor resources matching the supplied filters. May be empty, contain a single resource, or multiple resources.
  elements: dict
  returned: always
  type: list
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            filters=dict(
                type="list",
                elements="str",
            ),
        ),
        supports_check_mode=True,
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    # info modules only require the "collection" url
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://binaryauthorization.googleapis.com/v1/", base_uri="projects/{project}/attestors", configs={}
    )

    info = gcp_v2.Resource(
        module.params,  # only need it to build the link
        module=module,
        product="BinaryAuthorization",
        kind="binaryauthorization#attestor",
        op_configs=op_configs,
    )

    filter_exprs = module.params.get("filters") or []

    link = info.build_link("list")
    resources = info.list(link, key="attestors", filters=filter_exprs)

    module.exit_json(changed=False, resources=gcp_v2.filter_reserved_keys(resources))


if __name__ == "__main__":
    main()
