#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - '''DeploymentResourcePool can be shared by multiple deployed models,'
  - whose underlying specification consists of dedicated resources.'
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_vertexai_deployment_resource_pool
notes:
  - 'API Reference: U(https://cloud.google.com/vertex-ai/docs/reference/rest/v1/projects.locations.deploymentResourcePools)'
options:
  dedicated_resources:
    description:
      - The underlying dedicated resources that the deployment resource pool uses.
    suboptions:
      autoscaling_metric_specs:
        description:
          - A list of the metric specifications that overrides a resource utilization metric.
          - This property is immutable, to change it, you must delete and recreate the resource.
        elements: dict
        suboptions:
          metric_name:
            description:
              - The resource metric name.
              - 'Supported metrics: For Online Prediction: * `aiplatform.googleapis.com/prediction/online/accelerator/duty_cycle` * `aiplatform.googleapis.com/prediction/online/cpu/utilization`.'
            required: true
            type: str
          target:
            description:
              - The target resource utilization in percentage (1% - 100%) for the given metric; once the real usage deviates from the target by a certain percentage, the machine replicas change.
              - The default value is 60 (representing 60%) if not provided.
            type: int
        type: list
      machine_spec:
        description:
          - The specification of a single machine used by the prediction.
          - This property is immutable, to change it, you must delete and recreate the resource.
        required: true
        suboptions:
          accelerator_count:
            description:
              - The number of accelerators to attach to the machine.
            type: int
          accelerator_type:
            description:
              - The type of accelerator(s) that may be attached to the machine as per accelerator_count.
              - See possible values [here](https://cloud.google.com/vertex-ai/docs/reference/rest/v1/MachineSpec#AcceleratorType).
            type: str
          machine_type:
            description:
              - The type of the machine.
              - See the [list of machine types supported for prediction](https://cloud.google.com/vertex-ai/docs/predictions/configure-compute#machine-types).
              - This property is immutable, to change it, you must delete and recreate the resource.
            type: str
        type: dict
      max_replica_count:
        description:
          - The maximum number of replicas this DeployedModel may be deployed on when the traffic against it increases.
          - If the requested value is too large, the deployment will error, but if deployment succeeds then the ability to scale the model to that many replicas is guaranteed (barring service outages).
          - If traffic against the DeployedModel increases beyond what its replicas at maximum may handle, a portion of the traffic will be dropped.
          - If this value is not provided, will use min_replica_count as the default value.
          - The value of this field impacts the charge against Vertex CPU and GPU quotas.
          - Specifically, you will be charged for max_replica_count * number of cores in the selected machine type) and (max_replica_count * number of GPUs per replica in the selected machine type).
          - This property is immutable, to change it, you must delete and recreate the resource.
        type: int
      min_replica_count:
        description:
          - The minimum number of machine replicas this DeployedModel will be always deployed on.
          - This value must be greater than or equal to 1.
          - If traffic against the DeployedModel increases, it may dynamically be deployed onto more replicas, and as traffic decreases, some of these extra replicas may be freed.
          - This property is immutable, to change it, you must delete and recreate the resource.
        required: true
        type: int
    type: dict
  name:
    description:
      - The resource name of deployment resource pool.
      - The maximum length is 63 characters, and valid characters are `/^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$/`.
      - This property is immutable, to change it, you must delete and recreate the resource.
    required: true
    type: str
  region:
    description:
      - The region of deployment resource pool.
      - eg us-central1.
      - This property is immutable, to change it, you must delete and recreate the resource.
    type: str
  state:
    choices:
      - present
      - absent
    default: present
    description:
      - Whether the resource should exist in GCP.
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: Creates a GCP VertexAI.DeploymentResourcePool resource
"""  # noqa: E501

EXAMPLES = r"""
- name: Create Deployment Resource Pool
  google.cloud.gcp_vertexai_deployment_resource_pool:
    state: present
    name: my_deployment_resource_pool
    dedicated_resources:
      min_replica_count: 1
      max_replica_count: 3
      machine_spec:
        machine_type: n1-standard-4
        accelerator_type: NVIDIA_TESLA_P4
        accelerator_count: 1
    region: us-central1
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether the resource was changed.
  returned: always
  type: bool
createTime:
  description:
    - A timestamp in RFC3339 UTC "Zulu" format, with nanosecond resolution and up to nine fractional digits.
  returned: success
  type: str
state:
  description: The current state of the resource.
  returned: always
  type: str
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2

# BEGIN Custom imports
import copy

# END Custom imports


class DedicatedResources(gcp_v2.Resource):
    def _request(self):
        return {
            "autoscalingMetricSpecs": [
                DedicatedResourcesAutoscalingMetricSpec(item).to_request()
                for item in (self.request.get("autoscaling_metric_specs") or [])
            ],
            "machineSpec": gcp_v2.remove_empties(
                DedicatedResourcesMachineSpec(self.request.get("machine_spec", {})).to_request()
            ),  # remove empty values
            "maxReplicaCount": self.request.get("max_replica_count"),
            "minReplicaCount": self.request.get("min_replica_count"),
        }


class DedicatedResourcesAutoscalingMetricSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "metricName": self.request.get("metric_name"),
            "target": self.request.get("target"),
        }


class DedicatedResourcesMachineSpec(gcp_v2.Resource):
    def _request(self):
        return {
            "acceleratorCount": self.request.get("accelerator_count"),
            "acceleratorType": self.request.get("accelerator_type"),
            "machineType": self.request.get("machine_type"),
        }


class VertexAI(gcp_v2.Resource):
    def _request(self):
        return {
            "dedicatedResources": gcp_v2.remove_empties(
                DedicatedResources(self.request.get("dedicated_resources", {})).to_request()
            ),  # remove empty values
            "name": self.request.get("name"),
        }

    def _response(self):
        return {
            "createTime": self.response.get("createTime"),
        }

    def encode(self, request):
        "Custom encoder function, mutates the request object before it is sent to the API."

        # --------- BEGIN custom encoder code ---------
        self.debug(func="encoder", request=request, encoded=False)
        action = getattr(self, "_action", "read")
        r = {}
        if action == "create":
            r = {
                "deploymentResourcePool": copy.deepcopy(request),
                "deploymentResourcePoolId": request["name"],
            }
        elif action == "read":
            r = copy.deepcopy(request)
        elif action == "update":
            r = copy.deepcopy(request)
        else:
            pass

        self.debug(func="encoder", request=request, encoded=True)

        return r

        # --------- END custom encoder code ---------


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            name=dict(
                type="str",
                required=True,
            ),
            state=dict(
                type="str",
                default="present",
                choices=["present", "absent"],
            ),
            dedicated_resources=dict(
                type="dict",
                options=dict(
                    autoscaling_metric_specs=dict(
                        type="list",
                        elements="dict",
                        options=dict(
                            metric_name=dict(
                                type="str",
                                required=True,
                            ),
                            target=dict(
                                type="int",
                            ),
                        ),
                    ),
                    machine_spec=dict(
                        type="dict",
                        required=True,
                        options=dict(
                            accelerator_count=dict(
                                type="int",
                            ),
                            accelerator_type=dict(
                                type="str",
                            ),
                            machine_type=dict(
                                type="str",
                            ),
                        ),
                    ),
                    max_replica_count=dict(
                        type="int",
                    ),
                    min_replica_count=dict(
                        type="int",
                        required=True,
                    ),
                ),
            ),
            region=dict(
                type="str",
            ),
        )
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    state = module.params["state"]
    changed = False
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://{region}-aiplatform.googleapis.com/v1/",
        base_uri="projects/{project}/locations/{region}/deploymentResourcePools",
        configs={
            "create": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/deploymentResourcePools",
                    "async_uri": "{op_id}",
                    "verb": "POST",
                    "timeout_minutes": 20,
                }
            ),
            "delete": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/deploymentResourcePools/{name}",
                    "async_uri": "{op_id}",
                    "verb": "DELETE",
                    "timeout_minutes": 20,
                }
            ),
            "read": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/deploymentResourcePools/{name}",
                    "async_uri": "",
                    "verb": "GET",
                    "timeout_minutes": 0,
                }
            ),
            "update": gcp_v2.ResourceOpConfig(
                **{
                    "uri": "projects/{project}/locations/{region}/deploymentResourcePools/{name}",
                    "async_uri": "",
                    "verb": "PATCH",
                    "timeout_minutes": 20,
                }
            ),
        },
    )

    request = gcp_v2.remove_nones(module.params)
    resource = VertexAI(
        request, module=module, product="VertexAI", kind="vertexai#deploymentResourcePool", op_configs=op_configs
    )

    resource._state = state  # store the state in the resource object

    # Set this variable in one of the pre steps to implement custom diff logic
    custom_diff = None

    # BEGIN massaging ResourceRef properties
    # END massaging ResourceRef properties

    read_link: str = ""  # give it a chance for pre-read to overload

    if read_link == "":
        read_link = resource.build_link("read")
    existing_obj = resource.from_response(resource.get(read_link, allow_not_found=True) or {})
    new_obj = {}
    gcp_v2.debug(module, request=gcp_v2.remove_empties(resource.to_request()), existing=existing_obj, post=False)

    if custom_diff is not None:
        is_different = custom_diff
    else:
        is_different = resource.diff(gcp_v2.remove_empties(existing_obj))

    gcp_v2.debug(
        module,
        request=gcp_v2.remove_empties(resource.to_request()),
        existing=existing_obj,
        post=True,
        is_different=is_different,
    )

    if gcp_v2.empty(existing_obj):
        if state == "present":
            gcp_v2.debug(module, action="create")
            try:
                # --------- BEGIN create code ---------
                create_link: str = ""  # give it a chance for pre-create to overload
                # --------- BEGIN pre-create custom code ---------
                resource._action = "create"

                # --------- END pre-create custom code ---------
                if create_link == "":
                    create_link = resource.build_link("create")
                create_retries = op_configs.create.timeout
                create_func = getattr(resource, op_configs.create.verb)
                create_async_uri = op_configs.create.async_uri
                create_async_func = getattr(resource, op_configs.create.verb + "_async")
                gcp_v2.debug(module, msg="Creating resource", create_link=create_link, async_uri=create_async_uri)

                if create_async_uri != "":
                    new_obj = create_async_func(create_link, async_uri=create_async_uri, retries=create_retries)
                else:
                    new_obj = create_func(create_link)
                new_obj = resource.with_kind(resource.from_response(new_obj))
                gcp_v2.debug(module, new=new_obj, action="create", post=False)
                gcp_v2.debug(module, new=new_obj, action="create", post=True)
                # --------- END create code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            pass  # nothing to do
    else:
        if state == "absent":
            gcp_v2.debug(module, action="delete")
            try:
                # --------- BEGIN delete code ---------
                delete_link: str = ""  # give it a chance for pre-delete to overload
                # --------- BEGIN pre-delete custom code ---------
                resource._action = "delete"

                # --------- END pre-delete custom code ---------
                if delete_link == "":
                    delete_link = resource.build_link("delete")
                delete_retries = op_configs.delete.timeout
                delete_func = getattr(resource, op_configs.delete.verb)
                delete_async_uri = op_configs.delete.async_uri
                delete_async_func = getattr(resource, op_configs.delete.verb + "_async")
                gcp_v2.debug(
                    module,
                    msg="Destroying resource",
                    delete_link=delete_link,
                    async_uri=delete_async_uri,
                )

                if delete_async_uri != "":
                    new_obj = delete_async_func(delete_link, async_uri=delete_async_uri, retries=delete_retries)
                else:
                    new_obj = delete_func(delete_link)
                new_obj = resource.from_response(new_obj)
                gcp_v2.debug(module, new=new_obj, action="delete", post=False)
                gcp_v2.debug(module, new=new_obj, action="delete", post=True)
                # --------- END delete code ---------
            except Exception as e:
                module.fail_json(msg=str(e))

            changed = True
        else:
            if is_different:
                gcp_v2.debug(module, action="update")
                try:
                    # --------- BEGIN update code ---------
                    update_link: str = ""  # give it a chance for pre-update to overload
                    # --------- BEGIN pre-update custom code ---------
                    resource._action = "update"
                    update_link = resource.build_link("update") + "?updateMask=" + ",".join(resource.dot_fields())

                    # --------- END pre-update custom code ---------
                    if update_link == "":
                        update_link = resource.build_link("update")
                    update_retries = op_configs.update.timeout
                    update_func = getattr(resource, op_configs.update.verb)
                    update_async_uri = op_configs.update.async_uri
                    update_async_func = getattr(resource, op_configs.update.verb + "_async")
                    gcp_v2.debug(
                        module,
                        msg="Updating resource",
                        update_link=update_link,
                        async_uri=update_async_uri,
                    )
                    if update_async_uri != "":
                        new_obj = update_async_func(update_link, async_uri=update_async_uri, retries=update_retries)
                    else:
                        new_obj = update_func(update_link)
                    new_obj = resource.with_kind(resource.from_response(new_obj))
                    gcp_v2.debug(module, new=new_obj, action="update", post=False)
                    gcp_v2.debug(module, new=new_obj, action="update", post=True)
                    # --------- END update code ---------
                except Exception as e:
                    module.fail_json(msg=str(e))

                changed = True
            else:
                new_obj = existing_obj

    new_obj.update({"changed": changed})
    gcp_v2.debug(module, final_obj=new_obj, changed=changed)
    module.exit_json(**new_obj)


if __name__ == "__main__":
    main()
