#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017-2026 Google
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
# ----------------------------------------------------------------------------
#
#     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
#
# ----------------------------------------------------------------------------
#
#     This file is automatically generated by Magic Modules and manual
#     changes will be clobbered when the file is regenerated.
#
# ----------------------------------------------------------------------------
#

from __future__ import absolute_import, division, print_function

__metaclass__ = type

################################################################################
# Documentation
################################################################################

ANSIBLE_METADATA = {
    "metadata_version": "1.1",
    "status": ["preview"],
    "supported_by": "community",
}

DOCUMENTATION = r"""
---
author:
  - Google Inc. (@googlecloudplatform)
description:
  - A repository associated to a parent connection.
extends_documentation_fragment:
  - google.cloud.gcp
module: gcp_cloudbuildv2_repository_info
notes:
  - 'API Reference: U(https://cloud.google.com/build/docs/api/reference/rest)'
  - 'Official Documentation Guide: U(https://cloud.google.com/build/docs)'
options:
  filters:
    description:
      - A list of filter expression strings used to filter the resources returned by the API.
      - Each string is a filter expression (e.g. C(some_field = "SOME_VALUE")).
      - Multiple expressions are combined with a logical AND.
      - Refer to the filter topic documentation U(https://cloud.google.com/sdk/gcloud/reference/topic/filters).
      - Refer to the IAP-160 filter syntax documentation U(https://google.aip.dev/160).
    elements: str
    type: list
  parent_connection:
    description:
      - The connection for the resource.
    required: true
    type: str
requirements:
  - python >= 3.8
  - requests >= 2.18.4
  - google-auth >= 2.25.1
short_description: List GCP cloudbuildv2.Repository resources
"""  # noqa: E501

EXAMPLES = r"""
- name: List all gcp_cloudbuildv2_repository_info resources
  google.cloud.gcp_cloudbuildv2_repository_info:
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result

- name: List gcp_cloudbuildv2_repository_info resources matching given filters
  google.cloud.gcp_cloudbuildv2_repository_info:
    filters:
      - display_name = "my-resource"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
  register: result"""  # noqa: E501

RETURN = r"""
changed:
  description: Whether any changes were made (always false for info modules).
  returned: always
  type: bool
resources:
  contains:
    annotations:
      description:
        - Allows clients to store small amounts of arbitrary data.
        - '**Note**: This field is non-authoritative, and will only manage the annotations present in your configuration.'
      returned: when set
      type: dict
    createTime:
      description:
        - Output only.
        - Server assigned timestamp for when the connection was created.
      returned: success
      type: str
    etag:
      description:
        - This checksum is computed by the server based on the value of other fields, and may be sent on update and delete requests to ensure the client has an up-to-date value before proceeding.
      returned: success
      type: str
    remoteUri:
      description:
        - Git Clone HTTPS URI.
      returned: always
      type: str
    updateTime:
      description:
        - Output only.
        - Server assigned timestamp for when the connection was updated.
      returned: success
      type: str
  description: List of Cloudbuildv2.Repository resources matching the supplied filters. May be empty, contain a single resource, or multiple resources.
  elements: dict
  returned: always
  type: list
"""  # noqa: E501

################################################################################
# Imports
################################################################################

from ansible_collections.google.cloud.plugins.module_utils import gcp_v2


################################################################################
# Main
################################################################################


def main():
    """Main function"""

    module = gcp_v2.Module(
        argument_spec=dict(
            filters=dict(
                type="list",
                elements="str",
            ),
            parent_connection=dict(
                type="str",
                required=True,
            ),
        ),
        supports_check_mode=True,
    )

    if not module.params["scopes"]:
        module.params["scopes"] = ["https://www.googleapis.com/auth/cloud-platform"]

    # info modules only require the "collection" url
    op_configs = gcp_v2.ResourceOpConfigs(
        base_url="https://cloudbuild.googleapis.com/v2/", base_uri="{parent_connection}/repositories", configs={}
    )

    info = gcp_v2.Resource(
        module.params,  # only need it to build the link
        module=module,
        product="Cloudbuildv2",
        kind="cloudbuildv2#repository",
        op_configs=op_configs,
    )

    filter_exprs = module.params.get("filters") or []

    link = info.build_link("list")
    resources = info.list(link, key="repositories", filters=filter_exprs)

    module.exit_json(changed=False, resources=resources)


if __name__ == "__main__":
    main()
