---
name: Collection health checks
on:
  pull_request:
    paths:
      - 'meta/**'
      - 'plugins/modules/**'
jobs:
  check-meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - id: python-check-meta
        run: python .github/check-meta.py
